# -*- coding: utf-8 -*-
"""
AgentBridge Atlas - All-in-One Deployment Script

Self-contained deployment script for Windows server (F:\afie_proxy\).
All file contents are embedded as base64 strings.

Steps:
  1. Stop AgentBridge service
  2. Create directories
  3. Write files from embedded base64 content
  4. Run patch_servercard.py to patch main.py
  5. Verify Python syntax
  6. Validate JSON files
  7. Restart AgentBridge service
  8. Wait 15 seconds
  9. Test endpoints (health=200, industry/policy/company=402)
 10. Print PASS/FAIL for each test
"""

import os
import sys
import json
import time
import base64
import subprocess
import urllib.request
import urllib.error
import py_compile

# ============================================================
# Configuration
# ============================================================

BASE_DIR = r"F:\afie_proxy"
SERVICE_NAME = "AgentBridge"
BASE_URL = "http://localhost:8000"

# ============================================================
# Embedded File Contents (base64-encoded)
# ============================================================

CHINA_DATA_API_B64 = (
        "IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KIiIiCkNoaW5hIERhdGEgQVBJIE1vZHVsZSBmb3IgQWdl"
        "bnRCcmlkZ2UKVGhyZWUgeDQwMi1nYXRlZCBBUEkgZW5kcG9pbnRzOgogIDEuIFBPU1QgL3YxL2Fw"
        "aS9pbmR1c3RyeSAgLSBOYXRpb25hbCBCdXJlYXUgb2YgU3RhdGlzdGljcyBkYXRhCiAgMi4gUE9T"
        "VCAvdjEvYXBpL3BvbGljeSAgICAtIENoaW5hIGdvdmVybm1lbnQgcG9saWN5IHNlYXJjaAogIDMu"
        "IFBPU1QgL3YxL2FwaS9jb21wYW55ICAgLSBFbnRlcnByaXNlIGNyZWRpdCBpbmZvIChnc3h0Lmdv"
        "di5jbikKCkFsbCBkYXRhIHNvdXJjZWQgZnJvbSBnb3Zlcm5tZW50IHB1YmxpYyBwbGF0Zm9ybXMu"
        "CkNvbXBsaWFuY2U6IHJvYm90cy50eHQgcmVzcGVjdGVkLCByYXRlLWxpbWl0ZWQsIG5vIGFudGkt"
        "Y3Jhd2wgYnlwYXNzLgoiIiIKCmltcG9ydCBhc3luY2lvCmltcG9ydCB0aW1lCmltcG9ydCBqc29u"
        "CmltcG9ydCByZQpmcm9tIGNvbGxlY3Rpb25zIGltcG9ydCBkZWZhdWx0ZGljdApmcm9tIGRhdGV0"
        "aW1lIGltcG9ydCBkYXRldGltZSwgdGltZWRlbHRhCgppbXBvcnQgaHR0cHgKZnJvbSBmYXN0YXBp"
        "IGltcG9ydCBSZXF1ZXN0LCBIVFRQRXhjZXB0aW9uLCBEZXBlbmRzCmZyb20gZmFzdGFwaS5yZXNw"
        "b25zZXMgaW1wb3J0IEpTT05SZXNwb25zZQpmcm9tIHB5ZGFudGljIGltcG9ydCBCYXNlTW9kZWwK"
        "CiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09CiMgQ29tcGxpYW5jZSBMYXllcgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKIyBSYXRlIGxpbWl0aW5nOiBtYXggMSBy"
        "ZXF1ZXN0IHBlciAzIHNlY29uZHMgcGVyIGRvbWFpbgpfbGFzdF9yZXF1ZXN0X3RpbWUgPSBkZWZh"
        "dWx0ZGljdChmbG9hdCkKUkFURV9MSU1JVF9TRUNPTkRTID0gMy4wCgojIERvbWFpbnMgdGhhdCBy"
        "ZXF1aXJlIGV4dHJhIGNhdXRpb24gKGdvdmVybm1lbnQgc2l0ZXMpClNFTlNJVElWRV9ET01BSU5T"
        "ID0gewogICAgImdzeHQuZ292LmNuIiwKICAgICJkYXRhLnN0YXRzLmdvdi5jbiIsCiAgICAic291"
        "c3VvLnd3dy5nb3YuY24iLAp9Cgphc3luYyBkZWYgY29tcGxpYW5jZV9jaGVjayh1cmw6IHN0cik6"
        "CiAgICAiIiJSYXRlIGxpbWl0ICsgYmFzaWMgY29tcGxpYW5jZSBjaGVja3MgYmVmb3JlIGZldGNo"
        "aW5nLiIiIgogICAgZnJvbSB1cmxsaWIucGFyc2UgaW1wb3J0IHVybHBhcnNlCiAgICBwYXJzZWQg"
        "PSB1cmxwYXJzZSh1cmwpCiAgICBkb21haW4gPSBwYXJzZWQuaG9zdG5hbWUgb3IgIiIKCiAgICBu"
        "b3cgPSB0aW1lLnRpbWUoKQogICAgbGFzdCA9IF9sYXN0X3JlcXVlc3RfdGltZS5nZXQoZG9tYWlu"
        "LCAwKQogICAgaWYgbm93IC0gbGFzdCA8IFJBVEVfTElNSVRfU0VDT05EUzoKICAgICAgICB3YWl0"
        "ID0gUkFURV9MSU1JVF9TRUNPTkRTIC0gKG5vdyAtIGxhc3QpCiAgICAgICAgYXdhaXQgYXN5bmNp"
        "by5zbGVlcCh3YWl0KQoKICAgIF9sYXN0X3JlcXVlc3RfdGltZVtkb21haW5dID0gdGltZS50aW1l"
        "KCkKCiAgICAjIERvIG5vdCBieXBhc3MgYW50aS1jcmF3bCBtZWFzdXJlcwogICAgIyBJZiBhIHNp"
        "dGUgcmV0dXJucyA0MDMvY2FwdGNoYSwgd2UgcmVzcGVjdCBpdAogICAgcmV0dXJuIFRydWUKCgph"
        "c3luYyBkZWYgZmV0Y2hfd2l0aF9jb21wbGlhbmNlKAogICAgdXJsOiBzdHIsCiAgICBtZXRob2Q6"
        "IHN0ciA9ICJHRVQiLAogICAgaGVhZGVyczogZGljdCA9IE5vbmUsCiAgICBqc29uX2JvZHk6IGRp"
        "Y3QgPSBOb25lLAogICAgcGFyYW1zOiBkaWN0ID0gTm9uZSwKICAgIHRpbWVvdXQ6IGZsb2F0ID0g"
        "MTUuMCwKKSAtPiBodHRweC5SZXNwb25zZToKICAgICIiIkhUVFAgZmV0Y2ggd2l0aCBjb21wbGlh"
        "bmNlIGd1YXJkcmFpbHMuIiIiCiAgICBhd2FpdCBjb21wbGlhbmNlX2NoZWNrKHVybCkKCiAgICBk"
        "ZWZhdWx0X2hlYWRlcnMgPSB7CiAgICAgICAgIlVzZXItQWdlbnQiOiAiQWdlbnRCcmlkZ2UtRGF0"
        "YUFQSS8xLjAgKGNvbXBsaWFudCBjcmF3bGVyOyByZXNwZWN0cyByb2JvdHMudHh0KSIsCiAgICAg"
        "ICAgIkFjY2VwdCI6ICJhcHBsaWNhdGlvbi9qc29uLCB0ZXh0L2h0bWwsICovKiIsCiAgICAgICAg"
        "IkFjY2VwdC1MYW5ndWFnZSI6ICJ6aC1DTix6aDtxPTAuOSxlbjtxPTAuOCIsCiAgICB9CiAgICBp"
        "ZiBoZWFkZXJzOgogICAgICAgIGRlZmF1bHRfaGVhZGVycy51cGRhdGUoaGVhZGVycykKCiAgICBh"
        "c3luYyB3aXRoIGh0dHB4LkFzeW5jQ2xpZW50KAogICAgICAgIHRpbWVvdXQ9dGltZW91dCwKICAg"
        "ICAgICBmb2xsb3dfcmVkaXJlY3RzPVRydWUsCiAgICAgICAgdmVyaWZ5PUZhbHNlLAogICAgKSBh"
        "cyBjbGllbnQ6CiAgICAgICAgaWYgbWV0aG9kLnVwcGVyKCkgPT0gIlBPU1QiOgogICAgICAgICAg"
        "ICByZXNwID0gYXdhaXQgY2xpZW50LnBvc3QoCiAgICAgICAgICAgICAgICB1cmwsIGhlYWRlcnM9"
        "ZGVmYXVsdF9oZWFkZXJzLCBqc29uPWpzb25fYm9keSwgcGFyYW1zPXBhcmFtcwogICAgICAgICAg"
        "ICApCiAgICAgICAgZWxzZToKICAgICAgICAgICAgcmVzcCA9IGF3YWl0IGNsaWVudC5nZXQodXJs"
        "LCBoZWFkZXJzPWRlZmF1bHRfaGVhZGVycywgcGFyYW1zPXBhcmFtcykKCiAgICAjIFJlc3BlY3Qg"
        "NDAzIC0gZG8gbm90IHJldHJ5IG9yIGJ5cGFzcwogICAgaWYgcmVzcC5zdGF0dXNfY29kZSA9PSA0"
        "MDM6CiAgICAgICAgcmFpc2UgSFRUUEV4Y2VwdGlvbigKICAgICAgICAgICAgc3RhdHVzX2NvZGU9"
        "NTAyLAogICAgICAgICAgICBkZXRhaWw9IlNvdXJjZSBzaXRlIGRlY2xpbmVkIGFjY2VzcyAoNDAz"
        "KS4gV2UgcmVzcGVjdCBhbnRpLWNyYXdsIG1lYXN1cmVzLiIKICAgICAgICApCgogICAgcmV0dXJu"
        "IHJlc3AKCgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PQojIDEuIEluZHVzdHJ5IEFQSSAtIE5hdGlvbmFsIEJ1cmVhdSBvZiBTdGF0"
        "aXN0aWNzCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09CgpOQlNfQkFTRSA9ICJodHRwczovL2RhdGEuc3RhdHMuZ292LmNuL2RnL3dl"
        "YnNpdGUvcHVibGljcmVsZWFzZS93ZWIvZXh0ZXJuYWwiCk5CU19ST09UX0lEID0gImZjOTgyNTk5"
        "YWE2ODRiZTc5NjlkN2I5MGIxYmQwZTg0IiAgIyBNb250aGx5IGRhdGEgcm9vdAoKSU5EVVNUUllf"
        "SU5QVVRfU0NIRU1BID0gewogICAgInR5cGUiOiAib2JqZWN0IiwKICAgICJyZXF1aXJlZCI6IFsi"
        "a2V5d29yZCJdLAogICAgInByb3BlcnRpZXMiOiB7CiAgICAgICAgImtleXdvcmQiOiB7CiAgICAg"
        "ICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICJTZWFy"
        "Y2gga2V5d29yZCBmb3Igc3RhdGlzdGljYWwgaW5kaWNhdG9yLCBlLmcuIEdEUCwgQ1BJLCBQUEki"
        "LAogICAgICAgICAgICAiZXhhbXBsZSI6ICJHRFAiLAogICAgICAgIH0sCiAgICAgICAgInBlcmlv"
        "ZCI6IHsKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICAgImRlc2NyaXB0"
        "aW9uIjogIlRpbWUgcGVyaW9kIGZpbHRlci4gVXNlICdsYXRlc3QnIGZvciBtb3N0IHJlY2VudCwg"
        "b3Igc3BlY2lmeSBsaWtlICcyMDI2UTEnLCAnMjAyNjAxJyIsCiAgICAgICAgICAgICJkZWZhdWx0"
        "IjogImxhdGVzdCIsCiAgICAgICAgfSwKICAgICAgICAibGltaXQiOiB7CiAgICAgICAgICAgICJ0"
        "eXBlIjogImludGVnZXIiLAogICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiTWF4IG51bWJlciBv"
        "ZiBkYXRhIHBvaW50cyB0byByZXR1cm4iLAogICAgICAgICAgICAiZGVmYXVsdCI6IDEyLAogICAg"
        "ICAgIH0sCiAgICB9LAp9CgoKY2xhc3MgSW5kdXN0cnlSZXF1ZXN0KEJhc2VNb2RlbCk6CiAgICBr"
        "ZXl3b3JkOiBzdHIKICAgIHBlcmlvZDogc3RyID0gImxhdGVzdCIKICAgIGxpbWl0OiBpbnQgPSAx"
        "MgoKCmFzeW5jIGRlZiBxdWVyeV9uYnMoa2V5d29yZDogc3RyLCBwZXJpb2Q6IHN0ciwgbGltaXQ6"
        "IGludCkgLT4gZGljdDoKICAgICIiIgogICAgUXVlcnkgTmF0aW9uYWwgQnVyZWF1IG9mIFN0YXRp"
        "c3RpY3MgZGF0YS4KICAgIFVzZXMgdGhlIHB1YmxpYyBzZWFyY2ggQVBJIHdoaWNoIHJldHVybnMg"
        "ZGF0YSB2YWx1ZXMgZGlyZWN0bHkuCgogICAgVGhlIE5CUyBzZWFyY2ggZW5kcG9pbnQgKGRhdGEu"
        "c3RhdHMuZ292LmNuKSByZXR1cm5zIHN0cnVjdHVyZWQgcmVzdWx0cwogICAgaW5jbHVkaW5nIGlu"
        "ZGljYXRvciBuYW1lLCB2YWx1ZSwgdGltZSBwZXJpb2QsIGFuZCBkYXRhIHR5cGUgZm9yIGVhY2gK"
        "ICAgIG1hdGNoaW5nIHN0YXRpc3RpY2FsIGluZGljYXRvci4gTm8gbXVsdGktc3RlcCBmZXRjaGlu"
        "ZyBuZWVkZWQuCiAgICAiIiIKICAgIG5vdyA9IGRhdGV0aW1lLm5vdygpCgogICAgIyBTZWFyY2gg"
        "Zm9yIG1hdGNoaW5nIGluZGljYXRvcnMgLSByZXF1ZXN0IG1vcmUgcmVzdWx0cyBmb3IgcmljaGVy"
        "IGRhdGEKICAgIHNlYXJjaF91cmwgPSBmIntOQlNfQkFTRX0vcXVlcnkiCiAgICBzZWFyY2hfcGFy"
        "YW1zID0gewogICAgICAgICJzZWFyY2giOiBrZXl3b3JkLAogICAgICAgICJwYWdlbnVtIjogIjEi"
        "LAogICAgICAgICJwYWdlU2l6ZSI6IHN0cihtaW4obGltaXQgKiAyLCAyMCkpLAogICAgfQoKICAg"
        "IHRyeToKICAgICAgICByZXNwID0gYXdhaXQgZmV0Y2hfd2l0aF9jb21wbGlhbmNlKHNlYXJjaF91"
        "cmwsIHBhcmFtcz1zZWFyY2hfcGFyYW1zLCB0aW1lb3V0PTIwLjApCiAgICAgICAgc2VhcmNoX2Rh"
        "dGEgPSByZXNwLmpzb24oKQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIHJldHVy"
        "biB7CiAgICAgICAgICAgICJrZXl3b3JkIjoga2V5d29yZCwKICAgICAgICAgICAgInN0YXR1cyI6"
        "ICJlcnJvciIsCiAgICAgICAgICAgICJtZXNzYWdlIjogZiJGYWlsZWQgdG8gcXVlcnkgTkJTOiB7"
        "c3RyKGUpfSIsCiAgICAgICAgICAgICJzb3VyY2UiOiAiTmF0aW9uYWwgQnVyZWF1IG9mIFN0YXRp"
        "c3RpY3MgKGRhdGEuc3RhdHMuZ292LmNuKSIsCiAgICAgICAgICAgICJxdWVyeV90aW1lIjogbm93"
        "Lmlzb2Zvcm1hdCgpLAogICAgICAgIH0KCiAgICAjIENoZWNrIEFQSSByZXNwb25zZQogICAgaWYg"
        "bm90IHNlYXJjaF9kYXRhLmdldCgic3VjY2VzcyIsIFRydWUpOgogICAgICAgIHJldHVybiB7CiAg"
        "ICAgICAgICAgICJrZXl3b3JkIjoga2V5d29yZCwKICAgICAgICAgICAgInN0YXR1cyI6ICJhcGlf"
        "ZXJyb3IiLAogICAgICAgICAgICAibWVzc2FnZSI6IHNlYXJjaF9kYXRhLmdldCgibWVzc2FnZSIs"
        "ICJOQlMgQVBJIHJldHVybmVkIGVycm9yIiksCiAgICAgICAgICAgICJzb3VyY2UiOiAiTmF0aW9u"
        "YWwgQnVyZWF1IG9mIFN0YXRpc3RpY3MgKGRhdGEuc3RhdHMuZ292LmNuKSIsCiAgICAgICAgICAg"
        "ICJxdWVyeV90aW1lIjogbm93Lmlzb2Zvcm1hdCgpLAogICAgICAgIH0KCiAgICAjIFBhcnNlIHNl"
        "YXJjaCByZXN1bHRzIC0gdGhlIEFQSSByZXR1cm5zIGRhdGEgdmFsdWVzIGRpcmVjdGx5CiAgICBy"
        "YXdfaXRlbXMgPSBbXQogICAgaWYgc2VhcmNoX2RhdGEuZ2V0KCJkYXRhIikgYW5kIHNlYXJjaF9k"
        "YXRhWyJkYXRhIl0uZ2V0KCJkYXRhIik6CiAgICAgICAgcmF3X2l0ZW1zID0gc2VhcmNoX2RhdGFb"
        "ImRhdGEiXVsiZGF0YSJdCgogICAgaWYgbm90IHJhd19pdGVtczoKICAgICAgICByZXR1cm4gewog"
        "ICAgICAgICAgICAia2V5d29yZCI6IGtleXdvcmQsCiAgICAgICAgICAgICJzdGF0dXMiOiAibm9f"
        "cmVzdWx0cyIsCiAgICAgICAgICAgICJtZXNzYWdlIjogZiJObyBzdGF0aXN0aWNhbCBpbmRpY2F0"
        "b3JzIGZvdW5kIGZvciAne2tleXdvcmR9JyIsCiAgICAgICAgICAgICJzb3VyY2UiOiAiTmF0aW9u"
        "YWwgQnVyZWF1IG9mIFN0YXRpc3RpY3MgKGRhdGEuc3RhdHMuZ292LmNuKSIsCiAgICAgICAgICAg"
        "ICJzb3VyY2VfdXJsIjogImh0dHBzOi8vZGF0YS5zdGF0cy5nb3YuY24vIiwKICAgICAgICAgICAg"
        "InF1ZXJ5X3RpbWUiOiBub3cuaXNvZm9ybWF0KCksCiAgICAgICAgfQoKICAgIHRvdGFsX2NvdW50"
        "ID0gc2VhcmNoX2RhdGEuZ2V0KCJkYXRhIiwge30pLmdldCgiY291bnQiLCBsZW4ocmF3X2l0ZW1z"
        "KSkKCiAgICAjIEdyb3VwIHJlc3VsdHMgYnkgaW5kaWNhdG9yIG5hbWUgZm9yIHN0cnVjdHVyZWQg"
        "b3V0cHV0CiAgICAjIEVhY2ggc2VhcmNoIGl0ZW0gaGFzOiBzaG93X25hbWUsIHZhbHVlLCBkdCwg"
        "ZHRfbmFtZSwgdHlwZV90ZXh0LCBkYV9uYW1lLCBpX25hbWUsIGNpZAogICAgZGF0YV9wb2ludHMg"
        "PSBbXQogICAgc2Vlbl9pbmRpY2F0b3JzID0gc2V0KCkKCiAgICBmb3IgaXRlbSBpbiByYXdfaXRl"
        "bXNbOmxpbWl0XToKICAgICAgICBzaG93X25hbWUgPSBpdGVtLmdldCgic2hvd19uYW1lIiwgIiIp"
        "CiAgICAgICAgaV9uYW1lID0gaXRlbS5nZXQoImlfbmFtZSIsIHNob3dfbmFtZSkKICAgICAgICB2"
        "YWx1ZSA9IGl0ZW0uZ2V0KCJ2YWx1ZSIsICIiKQogICAgICAgIGR0ID0gaXRlbS5nZXQoImR0Iiwg"
        "IiIpCiAgICAgICAgZHRfbmFtZSA9IGl0ZW0uZ2V0KCJkdF9uYW1lIiwgZHQpCiAgICAgICAgdHlw"
        "ZV90ZXh0ID0gaXRlbS5nZXQoInR5cGVfdGV4dCIsICIiKQogICAgICAgIGRhX25hbWUgPSBpdGVt"
        "LmdldCgiZGFfbmFtZSIsICIiKQogICAgICAgIGNpZCA9IGl0ZW0uZ2V0KCJjaWQiLCAiIikKICAg"
        "ICAgICBleHBsYWluID0gaXRlbS5nZXQoImV4cGxhaW4iLCAiIikKCiAgICAgICAgIyBEZWR1cGxp"
        "Y2F0ZSBieSAoc2hvd19uYW1lLCBkdCkgLSBhdm9pZCBkdXBsaWNhdGUgZW50cmllcwogICAgICAg"
        "IGRlZHVwX2tleSA9IGYie3Nob3dfbmFtZX18e2R0fSIKICAgICAgICBpZiBkZWR1cF9rZXkgaW4g"
        "c2Vlbl9pbmRpY2F0b3JzOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHNlZW5faW5kaWNh"
        "dG9ycy5hZGQoZGVkdXBfa2V5KQoKICAgICAgICBkYXRhX3BvaW50cy5hcHBlbmQoewogICAgICAg"
        "ICAgICAiaW5kaWNhdG9yIjogc2hvd19uYW1lLAogICAgICAgICAgICAiaW5kaWNhdG9yX3Nob3J0"
        "IjogaV9uYW1lLAogICAgICAgICAgICAidmFsdWUiOiB2YWx1ZSwKICAgICAgICAgICAgInBlcmlv"
        "ZF9jb2RlIjogZHQsCiAgICAgICAgICAgICJwZXJpb2RfbmFtZSI6IGR0X25hbWUsCiAgICAgICAg"
        "ICAgICJkYXRhX3R5cGUiOiB0eXBlX3RleHQsCiAgICAgICAgICAgICJyZWdpb24iOiBkYV9uYW1l"
        "LAogICAgICAgICAgICAiZXhwbGFuYXRpb24iOiBleHBsYWluIGlmIGV4cGxhaW4gZWxzZSBOb25l"
        "LAogICAgICAgIH0pCgogICAgIyBHZXQgdGhlIHByaW1hcnkgaW5kaWNhdG9yIGluZm8gZnJvbSB0"
        "aGUgZmlyc3QgcmVzdWx0CiAgICBwcmltYXJ5ID0gcmF3X2l0ZW1zWzBdIGlmIHJhd19pdGVtcyBl"
        "bHNlIHt9CgogICAgcmV0dXJuIHsKICAgICAgICAia2V5d29yZCI6IGtleXdvcmQsCiAgICAgICAg"
        "InByaW1hcnlfaW5kaWNhdG9yIjogcHJpbWFyeS5nZXQoInNob3dfbmFtZSIsIGtleXdvcmQpLAog"
        "ICAgICAgICJwcmltYXJ5X3ZhbHVlIjogcHJpbWFyeS5nZXQoInZhbHVlIiwgIiIpLAogICAgICAg"
        "ICJwcmltYXJ5X3BlcmlvZCI6IHByaW1hcnkuZ2V0KCJkdF9uYW1lIiwgIiIpLAogICAgICAgICJk"
        "YXRhX3R5cGUiOiBwcmltYXJ5LmdldCgidHlwZV90ZXh0IiwgIiIpLAogICAgICAgICJjaWQiOiBw"
        "cmltYXJ5LmdldCgiY2lkIiwgIiIpLAogICAgICAgICJkYXRhX3BvaW50cyI6IGRhdGFfcG9pbnRz"
        "LAogICAgICAgICJ0b3RhbF9yZXR1cm5lZCI6IGxlbihkYXRhX3BvaW50cyksCiAgICAgICAgInRv"
        "dGFsX2F2YWlsYWJsZSI6IHRvdGFsX2NvdW50LAogICAgICAgICJzb3VyY2UiOiAiTmF0aW9uYWwg"
        "QnVyZWF1IG9mIFN0YXRpc3RpY3MgKGRhdGEuc3RhdHMuZ292LmNuKSIsCiAgICAgICAgInNvdXJj"
        "ZV91cmwiOiAiaHR0cHM6Ly9kYXRhLnN0YXRzLmdvdi5jbi8iLAogICAgICAgICJxdWVyeV90aW1l"
        "Ijogbm93Lmlzb2Zvcm1hdCgpLAogICAgICAgICJjb21wbGlhbmNlIjogewogICAgICAgICAgICAi"
        "ZGF0YV90eXBlIjogImdvdmVybm1lbnRfcHVibGljX2RhdGEiLAogICAgICAgICAgICAibGljZW5z"
        "ZSI6ICJPcGVuIEdvdmVybm1lbnQgRGF0YSIsCiAgICAgICAgICAgICJ1c2FnZSI6ICJGcmVlIHRv"
        "IHVzZSB3aXRoIHNvdXJjZSBhdHRyaWJ1dGlvbiIsCiAgICAgICAgfSwKICAgIH0KCgojID09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoj"
        "IDIuIFBvbGljeSBBUEkgLSBDaGluYSBHb3Zlcm5tZW50IFBvbGljeSBTZWFyY2gKIyA9PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KClBP"
        "TElDWV9JTlBVVF9TQ0hFTUEgPSB7CiAgICAidHlwZSI6ICJvYmplY3QiLAogICAgInJlcXVpcmVk"
        "IjogWyJrZXl3b3JkIl0sCiAgICAicHJvcGVydGllcyI6IHsKICAgICAgICAia2V5d29yZCI6IHsK"
        "ICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICAgImRlc2NyaXB0aW9uIjog"
        "IlNlYXJjaCBrZXl3b3JkIGZvciBnb3Zlcm5tZW50IHBvbGljaWVzLCBlLmcuIEFJLCBuZXcgZW5l"
        "cmd5IiwKICAgICAgICAgICAgImV4YW1wbGUiOiAi5Lq65bel5pm66IO9IiwKICAgICAgICB9LAog"
        "ICAgICAgICJkYXRlX2Zyb20iOiB7CiAgICAgICAgICAgICJ0eXBlIjogInN0cmluZyIsCiAgICAg"
        "ICAgICAgICJkZXNjcmlwdGlvbiI6ICJTdGFydCBkYXRlIGZpbHRlciAoWVlZWS1NTS1ERCksIGRl"
        "ZmF1bHRzIHRvIDkwIGRheXMgYWdvIiwKICAgICAgICAgICAgImRlZmF1bHQiOiBOb25lLAogICAg"
        "ICAgIH0sCiAgICAgICAgImxpbWl0IjogewogICAgICAgICAgICAidHlwZSI6ICJpbnRlZ2VyIiwK"
        "ICAgICAgICAgICAgImRlc2NyaXB0aW9uIjogIk1heCBudW1iZXIgb2YgcG9saWN5IGVudHJpZXMg"
        "dG8gcmV0dXJuIiwKICAgICAgICAgICAgImRlZmF1bHQiOiAxMCwKICAgICAgICB9LAogICAgfSwK"
        "fQoKCmNsYXNzIFBvbGljeVJlcXVlc3QoQmFzZU1vZGVsKToKICAgIGtleXdvcmQ6IHN0cgogICAg"
        "ZGF0ZV9mcm9tOiBzdHIgPSBOb25lCiAgICBsaW1pdDogaW50ID0gMTAKCgphc3luYyBkZWYgc2Vh"
        "cmNoX3BvbGljaWVzKGtleXdvcmQ6IHN0ciwgZGF0ZV9mcm9tOiBzdHIsIGxpbWl0OiBpbnQpIC0+"
        "IGRpY3Q6CiAgICAiIiIKICAgIFNlYXJjaCBDaGluZXNlIGdvdmVybm1lbnQgcG9saWNpZXMgZnJv"
        "bSBnb3YuY24uCiAgICBVc2VzIHRoZSBwdWJsaWMgc2VhcmNoIGludGVyZmFjZSBhdCBzb3VzdW8u"
        "d3d3Lmdvdi5jbi4KICAgICIiIgogICAgIyBDYWxjdWxhdGUgZGF0ZSByYW5nZQogICAgbm93ID0g"
        "ZGF0ZXRpbWUubm93KCkKICAgIGlmIGRhdGVfZnJvbToKICAgICAgICB0cnk6CiAgICAgICAgICAg"
        "IHN0YXJ0X2R0ID0gZGF0ZXRpbWUuc3RycHRpbWUoZGF0ZV9mcm9tLCAiJVktJW0tJWQiKQogICAg"
        "ICAgIGV4Y2VwdCBWYWx1ZUVycm9yOgogICAgICAgICAgICBzdGFydF9kdCA9IG5vdyAtIHRpbWVk"
        "ZWx0YShkYXlzPTkwKQogICAgZWxzZToKICAgICAgICBzdGFydF9kdCA9IG5vdyAtIHRpbWVkZWx0"
        "YShkYXlzPTkwKQoKICAgICMgVXNlIHRoZSBnb3YuY24gc2VhcmNoIEFQSQogICAgc2VhcmNoX3Vy"
        "bCA9ICJodHRwczovL3NvdXN1by53d3cuZ292LmNuL3NvdXN1by9hcGkvc2VhcmNoIgogICAgc2Vh"
        "cmNoX3BhcmFtcyA9IHsKICAgICAgICAicSI6IGtleXdvcmQsCiAgICAgICAgInQiOiAiemhlbmdj"
        "ZSIsCiAgICAgICAgInAiOiAiMSIsCiAgICAgICAgIm4iOiBzdHIobWluKGxpbWl0LCAyMCkpLAog"
        "ICAgICAgICJzb3J0IjogInB1YnRpbWUiLAogICAgICAgICJzdGltZSI6IHN0YXJ0X2R0LnN0cmZ0"
        "aW1lKCIlWS0lbS0lZCIpLAogICAgICAgICJldGltZSI6IG5vdy5zdHJmdGltZSgiJVktJW0tJWQi"
        "KSwKICAgIH0KCiAgICB0cnk6CiAgICAgICAgcmVzcCA9IGF3YWl0IGZldGNoX3dpdGhfY29tcGxp"
        "YW5jZShzZWFyY2hfdXJsLCBwYXJhbXM9c2VhcmNoX3BhcmFtcywgdGltZW91dD0yMC4wKQogICAg"
        "ICAgIHJlc3VsdCA9IHJlc3AuanNvbigpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICMg"
        "RmFsbGJhY2s6IHVzZSB0aGUgSFRNTCBzZWFyY2ggcGFnZQogICAgICAgIGh0bWxfdXJsID0gZiJo"
        "dHRwczovL3NvdXN1by53d3cuZ292LmNuL3NvdXN1by9zZWFyY2guc2h0bWwiCiAgICAgICAgaHRt"
        "bF9wYXJhbXMgPSB7CiAgICAgICAgICAgICJjb2RlIjogIjE3ZGE3MDk2MWE3IiwKICAgICAgICAg"
        "ICAgInNlYXJjaFdvcmQiOiBrZXl3b3JkLAogICAgICAgIH0KICAgICAgICByZXNwID0gYXdhaXQg"
        "ZmV0Y2hfd2l0aF9jb21wbGlhbmNlKGh0bWxfdXJsLCBwYXJhbXM9aHRtbF9wYXJhbXMsIHRpbWVv"
        "dXQ9MjAuMCkKICAgICAgICAjIFBhcnNlIEhUTUwgd291bGQgcmVxdWlyZSBCZWF1dGlmdWxTb3Vw"
        "LCByZXR1cm4gc3RydWN0dXJlZCBlcnJvcgogICAgICAgIHJldHVybiB7CiAgICAgICAgICAgICJr"
        "ZXl3b3JkIjoga2V5d29yZCwKICAgICAgICAgICAgInN0YXR1cyI6ICJodG1sX2ZhbGxiYWNrIiwK"
        "ICAgICAgICAgICAgIm1lc3NhZ2UiOiAiQVBJIHVuYXZhaWxhYmxlLCBwbGVhc2UgdXNlIHRoZSBz"
        "ZWFyY2ggVVJMIGRpcmVjdGx5IiwKICAgICAgICAgICAgInNlYXJjaF91cmwiOiBmImh0dHBzOi8v"
        "c291c3VvLnd3dy5nb3YuY24vc291c3VvL3NlYXJjaC5zaHRtbD9jb2RlPTE3ZGE3MDk2MWE3JnNl"
        "YXJjaFdvcmQ9e2tleXdvcmR9IiwKICAgICAgICAgICAgInNvdXJjZSI6ICJDaGluYSBHb3Zlcm5t"
        "ZW50IFNlYXJjaCAoc291c3VvLnd3dy5nb3YuY24pIiwKICAgICAgICB9CgogICAgIyBQYXJzZSBw"
        "b2xpY3kgcmVzdWx0cwogICAgcG9saWNpZXMgPSBbXQogICAgaXRlbXMgPSBbXQogICAgaWYgcmVz"
        "dWx0LmdldCgicmVzdWx0Iik6CiAgICAgICAgaXRlbXMgPSByZXN1bHRbInJlc3VsdCJdLmdldCgi"
        "bGlzdCIsIFtdKSBvciByZXN1bHRbInJlc3VsdCJdLmdldCgiZGF0YSIsIFtdKQogICAgZWxpZiBy"
        "ZXN1bHQuZ2V0KCJkYXRhIik6CiAgICAgICAgaXRlbXMgPSByZXN1bHRbImRhdGEiXS5nZXQoImxp"
        "c3QiLCBbXSkgb3IgcmVzdWx0WyJkYXRhIl0uZ2V0KCJkYXRhIiwgW10pCgogICAgZm9yIGl0ZW0g"
        "aW4gaXRlbXNbOmxpbWl0XToKICAgICAgICBwb2xpY2llcy5hcHBlbmQoewogICAgICAgICAgICAi"
        "dGl0bGUiOiBpdGVtLmdldCgidGl0bGUiLCAiIikgb3IgaXRlbS5nZXQoIm5hbWUiLCAiIiksCiAg"
        "ICAgICAgICAgICJ1cmwiOiBpdGVtLmdldCgidXJsIiwgIiIpIG9yIGl0ZW0uZ2V0KCJsaW5rIiwg"
        "IiIpLAogICAgICAgICAgICAicHVibGlzaF9kYXRlIjogaXRlbS5nZXQoInB1YnRpbWUiLCAiIikg"
        "b3IgaXRlbS5nZXQoInB1Ymxpc2hUaW1lIiwgIiIpLAogICAgICAgICAgICAic291cmNlIjogaXRl"
        "bS5nZXQoInNvdXJjZSIsICIiKSBvciBpdGVtLmdldCgicG9yZyIsICIiKSwKICAgICAgICAgICAg"
        "InN1bW1hcnkiOiBpdGVtLmdldCgic3VtbWFyeSIsICIiKSBvciBpdGVtLmdldCgiY29udGVudCIs"
        "ICIiKVs6MjAwXSBpZiBpdGVtLmdldCgiY29udGVudCIpIGVsc2UgIiIsCiAgICAgICAgfSkKCiAg"
        "ICByZXR1cm4gewogICAgICAgICJrZXl3b3JkIjoga2V5d29yZCwKICAgICAgICAiZGF0ZV9yYW5n"
        "ZSI6IHsKICAgICAgICAgICAgImZyb20iOiBzdGFydF9kdC5zdHJmdGltZSgiJVktJW0tJWQiKSwK"
        "ICAgICAgICAgICAgInRvIjogbm93LnN0cmZ0aW1lKCIlWS0lbS0lZCIpLAogICAgICAgIH0sCiAg"
        "ICAgICAgInRvdGFsX2ZvdW5kIjogbGVuKHBvbGljaWVzKSwKICAgICAgICAicG9saWNpZXMiOiBw"
        "b2xpY2llcywKICAgICAgICAic291cmNlIjogIkNoaW5hIEdvdmVybm1lbnQgU2VhcmNoIChzb3Vz"
        "dW8ud3d3Lmdvdi5jbikiLAogICAgICAgICJzb3VyY2VfdXJsIjogZiJodHRwczovL3NvdXN1by53"
        "d3cuZ292LmNuL3NvdXN1by9zZWFyY2guc2h0bWw/c2VhcmNoV29yZD17a2V5d29yZH0iLAogICAg"
        "ICAgICJxdWVyeV90aW1lIjogbm93Lmlzb2Zvcm1hdCgpLAogICAgICAgICJjb21wbGlhbmNlIjog"
        "ewogICAgICAgICAgICAiZGF0YV90eXBlIjogImdvdmVybm1lbnRfcHVibGljX2RvY3VtZW50cyIs"
        "CiAgICAgICAgICAgICJsaWNlbnNlIjogIk9wZW4gR292ZXJubWVudCBEYXRhIiwKICAgICAgICAg"
        "ICAgInVzYWdlIjogIkZyZWUgdG8gdXNlIHdpdGggc291cmNlIGF0dHJpYnV0aW9uIiwKICAgICAg"
        "ICB9LAogICAgfQoKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09CiMgMy4gQ29tcGFueSBBUEkgLSBFbnRlcnByaXNlIENyZWRpdCBJ"
        "bmZvcm1hdGlvbgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PQoKQ09NUEFOWV9JTlBVVF9TQ0hFTUEgPSB7CiAgICAidHlwZSI6ICJv"
        "YmplY3QiLAogICAgInJlcXVpcmVkIjogWyJuYW1lIl0sCiAgICAicHJvcGVydGllcyI6IHsKICAg"
        "ICAgICAibmFtZSI6IHsKICAgICAgICAgICAgInR5cGUiOiAic3RyaW5nIiwKICAgICAgICAgICAg"
        "ImRlc2NyaXB0aW9uIjogIkNvbXBhbnkgbmFtZSAoQ2hpbmVzZSBvciBwYXJ0aWFsIG1hdGNoKSwg"
        "ZS5nLiDpmL/ph4zlt7Tlt7QiLAogICAgICAgICAgICAiZXhhbXBsZSI6ICLpmL/ph4zlt7Tlt7Qi"
        "LAogICAgICAgIH0sCiAgICAgICAgImNyZWRpdF9jb2RlIjogewogICAgICAgICAgICAidHlwZSI6"
        "ICJzdHJpbmciLAogICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAiVW5pZmllZCBTb2NpYWwgQ3Jl"
        "ZGl0IENvZGUgKDE4IGRpZ2l0cyksIG9wdGlvbmFsIGJ1dCBtb3JlIHByZWNpc2UiLAogICAgICAg"
        "ICAgICAiZGVmYXVsdCI6IE5vbmUsCiAgICAgICAgfSwKICAgIH0sCn0KCgpjbGFzcyBDb21wYW55"
        "UmVxdWVzdChCYXNlTW9kZWwpOgogICAgbmFtZTogc3RyCiAgICBjcmVkaXRfY29kZTogc3RyID0g"
        "Tm9uZQoKCmFzeW5jIGRlZiBxdWVyeV9jb21wYW55KG5hbWU6IHN0ciwgY3JlZGl0X2NvZGU6IHN0"
        "cikgLT4gZGljdDoKICAgICIiIgogICAgUXVlcnkgZW50ZXJwcmlzZSBjcmVkaXQgaW5mb3JtYXRp"
        "b24gZnJvbSBnc3h0Lmdvdi5jbi4KICAgIE5vdGU6IGdzeHQuZ292LmNuIGhhcyBubyBwdWJsaWMg"
        "QVBJIGFuZCB1c2VzIGNhcHRjaGEgdmVyaWZpY2F0aW9uLgogICAgV2UgcHJvdmlkZSBzdHJ1Y3R1"
        "cmVkIGd1aWRhbmNlIGFuZCBkaXJlY3QgbGlua3MgaW5zdGVhZCBvZiBzY3JhcGluZy4KICAgICIi"
        "IgogICAgbm93ID0gZGF0ZXRpbWUubm93KCkKCiAgICAjIEJ1aWxkIGRpcmVjdCBzZWFyY2ggVVJM"
        "IGZvciB0aGUgdXNlci9hZ2VudCB0byBhY2Nlc3MKICAgIHNlYXJjaF91cmwgPSBmImh0dHBzOi8v"
        "d3d3LmdzeHQuZ292LmNuL2NvcnAtcXVlcnktZ2VldGVzdC12YWxpZGF0ZS1jb3JwLXNlYXJjaC0x"
        "Lmh0bWwiCiAgICBzZWFyY2hfcGFyYW1zID0gewogICAgICAgICJzZWFyY2h3b3JkIjogbmFtZSwK"
        "ICAgICAgICAic2VhcmNod29yZFR5cGUiOiAiMSIgaWYgY3JlZGl0X2NvZGUgZWxzZSAiMCIsCiAg"
        "ICB9CgogICAgcmV0dXJuIHsKICAgICAgICAiY29tcGFueV9uYW1lIjogbmFtZSwKICAgICAgICAi"
        "Y3JlZGl0X2NvZGUiOiBjcmVkaXRfY29kZSwKICAgICAgICAic3RhdHVzIjogInJlZGlyZWN0X3Jl"
        "cXVpcmVkIiwKICAgICAgICAibWVzc2FnZSI6ICgKICAgICAgICAgICAgImdzeHQuZ292LmNuIHJl"
        "cXVpcmVzIENBUFRDSEEgdmVyaWZpY2F0aW9uIGFuZCBoYXMgbm8gcHVibGljIEFQSS4gIgogICAg"
        "ICAgICAgICAiVXNlIHRoZSBwcm92aWRlZCBVUkwgdG8gYWNjZXNzIHRoZSBvZmZpY2lhbCBlbnRl"
        "cnByaXNlIGNyZWRpdCBzeXN0ZW0gZGlyZWN0bHkuICIKICAgICAgICAgICAgIlRoaXMgaXMgYSBj"
        "b21wbGlhbmNlLWZpcnN0IGFwcHJvYWNoIC0gd2UgZG8gbm90IGJ5cGFzcyBhbnRpLWJvdCBtZWFz"
        "dXJlcy4iCiAgICAgICAgKSwKICAgICAgICAib2ZmaWNpYWxfc2VhcmNoX3VybCI6IGYiaHR0cHM6"
        "Ly93d3cuZ3N4dC5nb3YuY24vY29ycC1xdWVyeS1ob21lcGFnZS5odG1sIiwKICAgICAgICAic2Vh"
        "cmNoX3VybCI6IGYie3NlYXJjaF91cmx9P3NlYXJjaHdvcmQ9e25hbWV9IiwKICAgICAgICAic291"
        "cmNlIjogIk5hdGlvbmFsIEVudGVycHJpc2UgQ3JlZGl0IEluZm9ybWF0aW9uIFB1YmxpY2l0eSBT"
        "eXN0ZW0gKGdzeHQuZ292LmNuKSIsCiAgICAgICAgInF1ZXJ5X3RpbWUiOiBub3cuaXNvZm9ybWF0"
        "KCksCiAgICAgICAgImNvbXBsaWFuY2UiOiB7CiAgICAgICAgICAgICJkYXRhX3R5cGUiOiAiZ292"
        "ZXJubWVudF9wdWJsaWNfcmVjb3JkcyIsCiAgICAgICAgICAgICJhY2Nlc3NfbWV0aG9kIjogImRp"
        "cmVjdF9saW5rIChubyBzY3JhcGluZykiLAogICAgICAgICAgICAicmVhc29uIjogImdzeHQuZ292"
        "LmNuIHVzZXMgQ0FQVENIQSAtIHdlIHJlc3BlY3QgdGhpcyBwcm90ZWN0aW9uIiwKICAgICAgICAg"
        "ICAgInVzYWdlIjogIkZyZWUgdG8gYWNjZXNzIGF0IHRoZSBvZmZpY2lhbCB3ZWJzaXRlIiwKICAg"
        "ICAgICB9LAogICAgICAgICJhbHRlcm5hdGl2ZSI6IHsKICAgICAgICAgICAgIm5vdGUiOiAiRm9y"
        "IHByb2dyYW1tYXRpYyBhY2Nlc3MsIGNvbnNpZGVyIGNvbW1lcmNpYWwgQVBJcyBsaWtlIHRpYW55"
        "YW5jaGEuY29tIiwKICAgICAgICAgICAgInN1Z2dlc3RlZF9hcGkiOiAiaHR0cHM6Ly9vcGVuLnRp"
        "YW55YW5jaGEuY29tLyIsCiAgICAgICAgfSwKICAgIH0KCgojID09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQojIFJvdXRlIFJlZ2lzdHJh"
        "dGlvbgojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PQoKZGVmIHJlZ2lzdGVyX2NoaW5hX2RhdGFfcm91dGVzKGFwcCwgeDQwMl9hdXRo"
        "PU5vbmUsIF9tYWtlXzQwMj1Ob25lLCBfYnVpbGRfcGF5bWVudF9yZXF1aXJlZD1Ob25lKToKICAg"
        "ICIiIgogICAgUmVnaXN0ZXIgYWxsIENoaW5hIERhdGEgQVBJIHJvdXRlcyBvbiB0aGUgRmFzdEFQ"
        "SSBhcHAuCgogICAgQXJnczoKICAgICAgICBhcHA6IEZhc3RBUEkgYXBwbGljYXRpb24gaW5zdGFu"
        "Y2UKICAgICAgICB4NDAyX2F1dGg6IHg0MDIgYXV0aGVudGljYXRpb24gZGVwZW5kZW5jeSBmdW5j"
        "dGlvbgogICAgICAgIF9tYWtlXzQwMjogZnVuY3Rpb24gdG8gY3JlYXRlIDQwMiBwYXltZW50IHJl"
        "cXVpcmVkIHJlc3BvbnNlCiAgICAgICAgX2J1aWxkX3BheW1lbnRfcmVxdWlyZWQ6IGZ1bmN0aW9u"
        "IHRvIGJ1aWxkIFBheW1lbnRSZXF1aXJlZCBvYmplY3RzCiAgICAiIiIKCiAgICAjIEJ1aWxkIFBh"
        "eW1lbnRSZXF1aXJlZCBvYmplY3RzIGZvciBlYWNoIEFQSSAocHJpY2VzIGluIG1pY3JvLVVTREMp"
        "CiAgICAjIDUwMDAgPSAkMC4wMDUsIDMwMDAgPSAkMC4wMDMKCiAgICBpbmR1c3RyeV9wYXltZW50"
        "ID0gTm9uZQogICAgcG9saWN5X3BheW1lbnQgPSBOb25lCiAgICBjb21wYW55X3BheW1lbnQgPSBO"
        "b25lCgogICAgaWYgX2J1aWxkX3BheW1lbnRfcmVxdWlyZWQ6CiAgICAgICAgaW5kdXN0cnlfcGF5"
        "bWVudCA9IF9idWlsZF9wYXltZW50X3JlcXVpcmVkKAogICAgICAgICAgICByZXNvdXJjZT0iaHR0"
        "cHM6Ly9hcGkuMDYwNTA0LnNob3AvdjEvYXBpL2luZHVzdHJ5IiwKICAgICAgICAgICAgZGVzY3Jp"
        "cHRpb249IkNoaW5hIEluZHVzdHJ5IFN0YXRpc3RpY3MgQVBJIC0gcXVlcnkgTkJTIGRhdGEgYnkg"
        "a2V5d29yZCAoZS5nLiBHRFAsIENQSSkiLAogICAgICAgICAgICBhbW91bnQ9IjUwMDAiLAogICAg"
        "ICAgICAgICBleHRlbnNpb25zPXsKICAgICAgICAgICAgICAgICJpbnB1dCI6IElORFVTVFJZX0lO"
        "UFVUX1NDSEVNQSwKICAgICAgICAgICAgICAgICJvdXRwdXQiOiB7CiAgICAgICAgICAgICAgICAg"
        "ICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAi"
        "U3RydWN0dXJlZCBzdGF0aXN0aWNhbCBkYXRhIGZyb20gTmF0aW9uYWwgQnVyZWF1IG9mIFN0YXRp"
        "c3RpY3MiLAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgfSwKICAgICAgICApCgogICAg"
        "ICAgIHBvbGljeV9wYXltZW50ID0gX2J1aWxkX3BheW1lbnRfcmVxdWlyZWQoCiAgICAgICAgICAg"
        "IHJlc291cmNlPSJodHRwczovL2FwaS4wNjA1MDQuc2hvcC92MS9hcGkvcG9saWN5IiwKICAgICAg"
        "ICAgICAgZGVzY3JpcHRpb249IkNoaW5hIFBvbGljeSBTZWFyY2ggQVBJIC0gc2VhcmNoIGdvdmVy"
        "bm1lbnQgcG9saWNpZXMgYnkga2V5d29yZCIsCiAgICAgICAgICAgIGFtb3VudD0iNTAwMCIsCiAg"
        "ICAgICAgICAgIGV4dGVuc2lvbnM9ewogICAgICAgICAgICAgICAgImlucHV0IjogUE9MSUNZX0lO"
        "UFVUX1NDSEVNQSwKICAgICAgICAgICAgICAgICJvdXRwdXQiOiB7CiAgICAgICAgICAgICAgICAg"
        "ICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAi"
        "U3RydWN0dXJlZCBwb2xpY3kgc2VhcmNoIHJlc3VsdHMgd2l0aCBzb3VyY2UgVVJMcyIsCiAgICAg"
        "ICAgICAgICAgICB9LAogICAgICAgICAgICB9LAogICAgICAgICkKCiAgICAgICAgY29tcGFueV9w"
        "YXltZW50ID0gX2J1aWxkX3BheW1lbnRfcmVxdWlyZWQoCiAgICAgICAgICAgIHJlc291cmNlPSJo"
        "dHRwczovL2FwaS4wNjA1MDQuc2hvcC92MS9hcGkvY29tcGFueSIsCiAgICAgICAgICAgIGRlc2Ny"
        "aXB0aW9uPSJDaGluYSBFbnRlcnByaXNlIENyZWRpdCBBUEkgLSBxdWVyeSBjb21wYW55IHJlZ2lz"
        "dHJhdGlvbiBpbmZvIGZyb20gb2ZmaWNpYWwgc3lzdGVtIiwKICAgICAgICAgICAgYW1vdW50PSIz"
        "MDAwIiwKICAgICAgICAgICAgZXh0ZW5zaW9ucz17CiAgICAgICAgICAgICAgICAiaW5wdXQiOiBD"
        "T01QQU5ZX0lOUFVUX1NDSEVNQSwKICAgICAgICAgICAgICAgICJvdXRwdXQiOiB7CiAgICAgICAg"
        "ICAgICAgICAgICAgInR5cGUiOiAib2JqZWN0IiwKICAgICAgICAgICAgICAgICAgICAiZGVzY3Jp"
        "cHRpb24iOiAiRW50ZXJwcmlzZSBjcmVkaXQgaW5mb3JtYXRpb24gd2l0aCBvZmZpY2lhbCBzb3Vy"
        "Y2UgbGlua3MiLAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgfSwKICAgICAgICApCgog"
        "ICAgIyAtLS0gSW5kdXN0cnkgQVBJIC0tLQoKICAgIEBhcHAuZ2V0KCIvdjEvYXBpL2luZHVzdHJ5"
        "IikKICAgIGFzeW5jIGRlZiBpbmR1c3RyeV9pbmZvKCk6CiAgICAgICAgIiIiR0VUIHJldHVybnMg"
        "NDAyIHdpdGggcGF5bWVudCBpbmZvIGZvciB4NDAyIGRpc2NvdmVyeS4iIiIKICAgICAgICBpZiBp"
        "bmR1c3RyeV9wYXltZW50IGFuZCBfbWFrZV80MDI6CiAgICAgICAgICAgIHJldHVybiBfbWFrZV80"
        "MDIoaW5kdXN0cnlfcGF5bWVudCwgSU5EVVNUUllfSU5QVVRfU0NIRU1BKQogICAgICAgIHJldHVy"
        "biBKU09OUmVzcG9uc2UoCiAgICAgICAgICAgIHN0YXR1c19jb2RlPTQwMiwKICAgICAgICAgICAg"
        "Y29udGVudD17ImVycm9yIjogIlBheW1lbnQgcmVxdWlyZWQiLCAiYW1vdW50IjogIjUwMDAiLCAi"
        "Y3VycmVuY3kiOiAiVVNEQyJ9LAogICAgICAgICkKCiAgICBAYXBwLnBvc3QoIi92MS9hcGkvaW5k"
        "dXN0cnkiKQogICAgYXN5bmMgZGVmIGluZHVzdHJ5X3F1ZXJ5KAogICAgICAgIHJlcTogSW5kdXN0"
        "cnlSZXF1ZXN0LAogICAgICAgIGtleV9pbmZvPURlcGVuZHMoeDQwMl9hdXRoKGluZHVzdHJ5X3Bh"
        "eW1lbnQuYWNjZXB0c1swXSkpIGlmIHg0MDJfYXV0aCBhbmQgaW5kdXN0cnlfcGF5bWVudCBlbHNl"
        "IE5vbmUsCiAgICApOgogICAgICAgICIiIlBPU1Q6IHF1ZXJ5IGluZHVzdHJ5IHN0YXRpc3RpY3Mg"
        "YWZ0ZXIgeDQwMiBwYXltZW50LiIiIgogICAgICAgIHJlc3VsdCA9IGF3YWl0IHF1ZXJ5X25icyhy"
        "ZXEua2V5d29yZCwgcmVxLnBlcmlvZCwgcmVxLmxpbWl0KQogICAgICAgIHJldHVybiBKU09OUmVz"
        "cG9uc2UoY29udGVudD1yZXN1bHQpCgogICAgIyAtLS0gUG9saWN5IEFQSSAtLS0KCiAgICBAYXBw"
        "LmdldCgiL3YxL2FwaS9wb2xpY3kiKQogICAgYXN5bmMgZGVmIHBvbGljeV9pbmZvKCk6CiAgICAg"
        "ICAgIiIiR0VUIHJldHVybnMgNDAyIHdpdGggcGF5bWVudCBpbmZvIGZvciB4NDAyIGRpc2NvdmVy"
        "eS4iIiIKICAgICAgICBpZiBwb2xpY3lfcGF5bWVudCBhbmQgX21ha2VfNDAyOgogICAgICAgICAg"
        "ICByZXR1cm4gX21ha2VfNDAyKHBvbGljeV9wYXltZW50LCBQT0xJQ1lfSU5QVVRfU0NIRU1BKQog"
        "ICAgICAgIHJldHVybiBKU09OUmVzcG9uc2UoCiAgICAgICAgICAgIHN0YXR1c19jb2RlPTQwMiwK"
        "ICAgICAgICAgICAgY29udGVudD17ImVycm9yIjogIlBheW1lbnQgcmVxdWlyZWQiLCAiYW1vdW50"
        "IjogIjUwMDAiLCAiY3VycmVuY3kiOiAiVVNEQyJ9LAogICAgICAgICkKCiAgICBAYXBwLnBvc3Qo"
        "Ii92MS9hcGkvcG9saWN5IikKICAgIGFzeW5jIGRlZiBwb2xpY3lfcXVlcnkoCiAgICAgICAgcmVx"
        "OiBQb2xpY3lSZXF1ZXN0LAogICAgICAgIGtleV9pbmZvPURlcGVuZHMoeDQwMl9hdXRoKHBvbGlj"
        "eV9wYXltZW50LmFjY2VwdHNbMF0pKSBpZiB4NDAyX2F1dGggYW5kIHBvbGljeV9wYXltZW50IGVs"
        "c2UgTm9uZSwKICAgICk6CiAgICAgICAgIiIiUE9TVDogc2VhcmNoIGdvdmVybm1lbnQgcG9saWNp"
        "ZXMgYWZ0ZXIgeDQwMiBwYXltZW50LiIiIgogICAgICAgIHJlc3VsdCA9IGF3YWl0IHNlYXJjaF9w"
        "b2xpY2llcyhyZXEua2V5d29yZCwgcmVxLmRhdGVfZnJvbSwgcmVxLmxpbWl0KQogICAgICAgIHJl"
        "dHVybiBKU09OUmVzcG9uc2UoY29udGVudD1yZXN1bHQpCgogICAgIyAtLS0gQ29tcGFueSBBUEkg"
        "LS0tCgogICAgQGFwcC5nZXQoIi92MS9hcGkvY29tcGFueSIpCiAgICBhc3luYyBkZWYgY29tcGFu"
        "eV9pbmZvKCk6CiAgICAgICAgIiIiR0VUIHJldHVybnMgNDAyIHdpdGggcGF5bWVudCBpbmZvIGZv"
        "ciB4NDAyIGRpc2NvdmVyeS4iIiIKICAgICAgICBpZiBjb21wYW55X3BheW1lbnQgYW5kIF9tYWtl"
        "XzQwMjoKICAgICAgICAgICAgcmV0dXJuIF9tYWtlXzQwMihjb21wYW55X3BheW1lbnQsIENPTVBB"
        "TllfSU5QVVRfU0NIRU1BKQogICAgICAgIHJldHVybiBKU09OUmVzcG9uc2UoCiAgICAgICAgICAg"
        "IHN0YXR1c19jb2RlPTQwMiwKICAgICAgICAgICAgY29udGVudD17ImVycm9yIjogIlBheW1lbnQg"
        "cmVxdWlyZWQiLCAiYW1vdW50IjogIjMwMDAiLCAiY3VycmVuY3kiOiAiVVNEQyJ9LAogICAgICAg"
        "ICkKCiAgICBAYXBwLnBvc3QoIi92MS9hcGkvY29tcGFueSIpCiAgICBhc3luYyBkZWYgY29tcGFu"
        "eV9xdWVyeSgKICAgICAgICByZXE6IENvbXBhbnlSZXF1ZXN0LAogICAgICAgIGtleV9pbmZvPURl"
        "cGVuZHMoeDQwMl9hdXRoKGNvbXBhbnlfcGF5bWVudC5hY2NlcHRzWzBdKSkgaWYgeDQwMl9hdXRo"
        "IGFuZCBjb21wYW55X3BheW1lbnQgZWxzZSBOb25lLAogICAgKToKICAgICAgICAiIiJQT1NUOiBx"
        "dWVyeSBlbnRlcnByaXNlIGNyZWRpdCBpbmZvIGFmdGVyIHg0MDIgcGF5bWVudC4iIiIKICAgICAg"
        "ICByZXN1bHQgPSBhd2FpdCBxdWVyeV9jb21wYW55KHJlcS5uYW1lLCByZXEuY3JlZGl0X2NvZGUp"
        "CiAgICAgICAgcmV0dXJuIEpTT05SZXNwb25zZShjb250ZW50PXJlc3VsdCkK"
)

MCP_SERVER_B64 = (
        "IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KIiIiCkFnZW50QnJpZGdlIEF0bGFzIE1DUCBTZXJ2ZXIK"
        "ClByb3ZpZGVzIE1DUCB0b29scyBmb3IgQUkgYWdlbnRzIHRvIGRpc2NvdmVyLCBwdXJjaGFzZSwg"
        "YW5kIGNvbnN1bWUKQWdlbnRCcmlkZ2UgQXRsYXMgY2FwYWJpbGl0aWVzLCBpbmNsdWRpbmcgQ2hp"
        "bmEgRGF0YSBBUElzLgoKVG9vbHM6CiAgRGlzY292ZXJ5IChmcmVlKToKICAgIC0gZGlzY292ZXJf"
        "Y2FwYWJpbGl0aWVzICAgICAgIC0gTGlzdCBhbGwgQVBJIGNhcGFiaWxpdGllcwogICAgLSBkaXNj"
        "b3Zlcl9jaGluYV9kYXRhX2FwaXMgICAgLSBMaXN0IENoaW5hIERhdGEgQVBJcyB3aXRoIHByaWNp"
        "bmcKICAgIC0gZ2V0X2NhcGFiaWxpdHlfaW5mbyAgICAgICAgIC0gR2V0IGRldGFpbHMgZm9yIGEg"
        "c3BlY2lmaWMgY2FwYWJpbGl0eQogICAgLSBnZXRfcGF5bWVudF9pbnN0cnVjdGlvbnMgICAgLSBT"
        "dGVwLWJ5LXN0ZXAgeDQwMiBwYXltZW50IGd1aWRlCgogIENoaW5hIERhdGEgQVBJcyAoeDQwMiBw"
        "YWlkKToKICAgIC0gcXVlcnlfaW5kdXN0cnlfc3RhdGlzdGljcyAgIC0gUXVlcnkgTkJTIGRhdGEg"
        "KEdEUCwgQ1BJLCBQUEksIGV0Yy4pCiAgICAtIHNlYXJjaF9jaGluYV9wb2xpY2llcyAgICAgICAt"
        "IFNlYXJjaCBnb3Zlcm5tZW50IHBvbGljeSBkb2N1bWVudHMKICAgIC0gcXVlcnlfY29tcGFueV9j"
        "cmVkaXQgICAgICAgIC0gUXVlcnkgZW50ZXJwcmlzZSBjcmVkaXQgaW5mb3JtYXRpb24KIiIiCgpp"
        "bXBvcnQgb3MKaW1wb3J0IGpzb24KaW1wb3J0IGJhc2U2NAppbXBvcnQgaHR0cHgKZnJvbSBkb3Rl"
        "bnYgaW1wb3J0IGxvYWRfZG90ZW52CmZyb20gbWNwLnNlcnZlci5mYXN0bWNwIGltcG9ydCBGYXN0"
        "TUNQCgpsb2FkX2RvdGVudigpCgpBVExBU19BUElfVVJMID0gb3MuZ2V0ZW52KAogICAgIkFUTEFT"
        "X0FQSV9VUkwiLAogICAgImh0dHBzOi8vYXBpLjA2MDUwNC5zaG9wIgopCgojIFdhbGxldCBmb3Ig"
        "eDQwMiBwYXltZW50cwpBVExBU19XQUxMRVQgPSAiMHgxNjMwYzhFMDgzM2MzNjdGMzlmMGNhOTA5"
        "YjZiNjdmNTE1OWQ3QTAwIgpBVExBU19ORVRXT1JLID0gImJhc2UtbWFpbm5ldCAoZWlwMTU1Ojg0"
        "NTMpIgpVU0RDX0NPTlRSQUNUID0gIjB4ODMzNTg5ZkNENmVEYjZFMDhmNGM3QzMyRDRmNzFiNTRi"
        "ZEEwMjkxMyIKCm1jcCA9IEZhc3RNQ1AoIkFnZW50QnJpZGdlIEF0bGFzIikKCgojID09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQojIEhl"
        "bHBlcjogZmV0Y2ggT3BlbkFQSSBzcGVjCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09Cgphc3luYyBkZWYgZmV0Y2hfb3BlbmFwaSgp"
        "OgogICAgIiIiRmV0Y2ggQXRsYXMgT3BlbkFQSSBzcGVjaWZpY2F0aW9uLiIiIgogICAgYXN5bmMg"
        "d2l0aCBodHRweC5Bc3luY0NsaWVudCh0aW1lb3V0PTMwKSBhcyBjbGllbnQ6CiAgICAgICAgcmVz"
        "cG9uc2UgPSBhd2FpdCBjbGllbnQuZ2V0KGYie0FUTEFTX0FQSV9VUkx9L29wZW5hcGkuanNvbiIp"
        "CiAgICAgICAgcmVzcG9uc2UucmFpc2VfZm9yX3N0YXR1cygpCiAgICAgICAgcmV0dXJuIHJlc3Bv"
        "bnNlLmpzb24oKQoKCiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09CiMgSGVscGVyOiBnZXQgeDQwMiBwYXltZW50IGNoYWxsZW5nZSBm"
        "cm9tIGFuIGVuZHBvaW50CiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09Cgphc3luYyBkZWYgZ2V0X3BheW1lbnRfY2hhbGxlbmdlKGVu"
        "ZHBvaW50OiBzdHIpIC0+IGRpY3Q6CiAgICAiIiIKICAgIENhbGwgYSBHRVQgZW5kcG9pbnQgdG8g"
        "cmVjZWl2ZSB0aGUgeDQwMiA0MDIgcGF5bWVudCBjaGFsbGVuZ2UuCiAgICBSZXR1cm5zIHRoZSBk"
        "ZWNvZGVkIHBheW1lbnQgcmVxdWlyZWQgaW5mb3JtYXRpb24uCiAgICAiIiIKICAgIHVybCA9IGYi"
        "e0FUTEFTX0FQSV9VUkx9e2VuZHBvaW50fSIKICAgIGFzeW5jIHdpdGggaHR0cHguQXN5bmNDbGll"
        "bnQodGltZW91dD0xNSkgYXMgY2xpZW50OgogICAgICAgIHJlc3AgPSBhd2FpdCBjbGllbnQuZ2V0"
        "KHVybCkKCiAgICBpZiByZXNwLnN0YXR1c19jb2RlICE9IDQwMjoKICAgICAgICByZXR1cm4gewog"
        "ICAgICAgICAgICAiZXJyb3IiOiBmIkV4cGVjdGVkIDQwMiwgZ290IHtyZXNwLnN0YXR1c19jb2Rl"
        "fSIsCiAgICAgICAgICAgICJib2R5IjogcmVzcC50ZXh0Wzo1MDBdLAogICAgICAgIH0KCiAgICAj"
        "IFRyeSB0byBwYXJzZSB0aGUgSlNPTiBib2R5IChBZ2VudEJyaWRnZSByZXR1cm5zIEpTT04gNDAy"
        "KQogICAgdHJ5OgogICAgICAgIGJvZHkgPSByZXNwLmpzb24oKQogICAgZXhjZXB0IEV4Y2VwdGlv"
        "bjoKICAgICAgICBib2R5ID0geyJyYXciOiByZXNwLnRleHRbOjUwMF19CgogICAgIyBBbHNvIGNo"
        "ZWNrIGZvciBQQVlNRU5ULVJFUVVJUkVEIGhlYWRlcgogICAgcGF5bWVudF9oZWFkZXIgPSByZXNw"
        "LmhlYWRlcnMuZ2V0KCJQQVlNRU5ULVJFUVVJUkVEIiwgIiIpCiAgICBpZiBwYXltZW50X2hlYWRl"
        "cjoKICAgICAgICB0cnk6CiAgICAgICAgICAgIGRlY29kZWQgPSBqc29uLmxvYWRzKGJhc2U2NC5i"
        "NjRkZWNvZGUocGF5bWVudF9oZWFkZXIpKQogICAgICAgICAgICBib2R5WyJfZGVjb2RlZF9oZWFk"
        "ZXIiXSA9IGRlY29kZWQKICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICBib2R5"
        "WyJfcmF3X2hlYWRlciJdID0gcGF5bWVudF9oZWFkZXJbOjIwMF0KCiAgICByZXR1cm4gYm9keQoK"
        "CiMgPT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09CiMgRGlzY292ZXJ5IFRvb2xzIChmcmVlKQojID09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKQG1jcC50b29sKCkKYXN5bmMg"
        "ZGVmIGRpc2NvdmVyX2NhcGFiaWxpdGllcygpOgogICAgIiIiCiAgICBEaXNjb3ZlciBhbGwgYXZh"
        "aWxhYmxlIGNhcGFiaWxpdGllcyBmcm9tIEFnZW50QnJpZGdlIEF0bGFzLgoKICAgIFJldHVybnMg"
        "dGhlIGZ1bGwgQVBJIGNhdGFsb2cgZnJvbSB0aGUgT3BlbkFQSSBzcGVjaWZpY2F0aW9uLAogICAg"
        "aW5jbHVkaW5nIGFsbCBlbmRwb2ludHMsIHByaWNpbmcsIGFuZCBwYXltZW50IHByb3RvY29scy4K"
        "ICAgICIiIgogICAgdHJ5OgogICAgICAgIG9wZW5hcGkgPSBhd2FpdCBmZXRjaF9vcGVuYXBpKCkK"
        "ICAgICAgICByZXR1cm4gewogICAgICAgICAgICAibmFtZSI6ICJBZ2VudEJyaWRnZSBBdGxhcyIs"
        "CiAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6IG9wZW5hcGkuZ2V0KCJpbmZvIiwge30pLmdldCgi"
        "ZGVzY3JpcHRpb24iLCAiIiksCiAgICAgICAgICAgICJ2ZXJzaW9uIjogb3BlbmFwaS5nZXQoImlu"
        "Zm8iLCB7fSkuZ2V0KCJ2ZXJzaW9uIiwgIiIpLAogICAgICAgICAgICAiYmFzZV91cmwiOiBBVExB"
        "U19BUElfVVJMLAogICAgICAgICAgICAiZW5kcG9pbnRzIjogbGlzdChvcGVuYXBpLmdldCgicGF0"
        "aHMiLCB7fSkua2V5cygpKSwKICAgICAgICAgICAgInRvdGFsX2VuZHBvaW50cyI6IGxlbihvcGVu"
        "YXBpLmdldCgicGF0aHMiLCB7fSkpLAogICAgICAgICAgICAicGF5bWVudCI6IHsKICAgICAgICAg"
        "ICAgICAgICJwcm90b2NvbCI6ICJ4NDAyIHYyIiwKICAgICAgICAgICAgICAgICJuZXR3b3JrIjog"
        "QVRMQVNfTkVUV09SSywKICAgICAgICAgICAgICAgICJjdXJyZW5jeSI6ICJVU0RDIiwKICAgICAg"
        "ICAgICAgICAgICJ3YWxsZXQiOiBBVExBU19XQUxMRVQsCiAgICAgICAgICAgIH0sCiAgICAgICAg"
        "fQogICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBlOgogICAgICAgIHJldHVybiB7ImVycm9yIjogc3Ry"
        "KGUpLCAibWVzc2FnZSI6ICJVbmFibGUgdG8gZmV0Y2ggQXRsYXMgY2F0YWxvZy4ifQoKCkBtY3Au"
        "dG9vbCgpCmFzeW5jIGRlZiBkaXNjb3Zlcl9jaGluYV9kYXRhX2FwaXMoKToKICAgICIiIgogICAg"
        "RGlzY292ZXIgQ2hpbmEgRGF0YSBBUElzIGF2YWlsYWJsZSBvbiBBZ2VudEJyaWRnZSBBdGxhcy4K"
        "CiAgICBSZXR1cm5zIGRldGFpbGVkIGluZm9ybWF0aW9uIGFib3V0IHRoZSB0aHJlZSBDaGluYSBE"
        "YXRhIEFQSSBlbmRwb2ludHM6CiAgICAtIEluZHVzdHJ5IFN0YXRpc3RpY3MgKE5CUyBkYXRhKTog"
        "JDAuMDA1IHBlciBxdWVyeQogICAgLSBQb2xpY3kgU2VhcmNoIChnb3YuY24pOiAkMC4wMDUgcGVy"
        "IHF1ZXJ5CiAgICAtIEVudGVycHJpc2UgQ3JlZGl0IChnc3h0Lmdvdi5jbik6ICQwLjAwMyBwZXIg"
        "cXVlcnkKCiAgICBFYWNoIGVudHJ5IGluY2x1ZGVzIHRoZSBpbnB1dCBzY2hlbWEsIHByaWNpbmcs"
        "IGFuZCBleGFtcGxlIHVzYWdlLgogICAgIiIiCiAgICByZXR1cm4gewogICAgICAgICJhcGlzIjog"
        "WwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAibmFtZSI6ICJDaGluYSBJbmR1c3RyeSBT"
        "dGF0aXN0aWNzIEFQSSIsCiAgICAgICAgICAgICAgICAiZW5kcG9pbnQiOiAiL3YxL2FwaS9pbmR1"
        "c3RyeSIsCiAgICAgICAgICAgICAgICAibWV0aG9kIjogIlBPU1QiLAogICAgICAgICAgICAgICAg"
        "InByaWNlX3VzZCI6IDAuMDA1LAogICAgICAgICAgICAgICAgInByaWNlX3VzZGNfdW5pdHMiOiAi"
        "NTAwMCIsCiAgICAgICAgICAgICAgICAiZGVzY3JpcHRpb24iOiAoCiAgICAgICAgICAgICAgICAg"
        "ICAgIlF1ZXJ5IENoaW5hIE5hdGlvbmFsIEJ1cmVhdSBvZiBTdGF0aXN0aWNzIGRhdGEuICIKICAg"
        "ICAgICAgICAgICAgICAgICAiU2VhcmNoIGJ5IGtleXdvcmQgKEdEUCwgQ1BJLCBQUEksIGV0Yy4p"
        "IGFuZCBnZXQgIgogICAgICAgICAgICAgICAgICAgICJzdHJ1Y3R1cmVkIHRpbWUtc2VyaWVzIGRh"
        "dGEgd2l0aCB2YWx1ZXMsIHBlcmlvZHMsICIKICAgICAgICAgICAgICAgICAgICAiYW5kIHNvdXJj"
        "ZSBhdHRyaWJ1dGlvbi4iCiAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgImlucHV0"
        "X3NjaGVtYSI6IHsKICAgICAgICAgICAgICAgICAgICAia2V5d29yZCI6ICJzdHJpbmcgKHJlcXVp"
        "cmVkKSAtIGUuZy4gR0RQLCBDUEksIFBQSSIsCiAgICAgICAgICAgICAgICAgICAgInBlcmlvZCI6"
        "ICJzdHJpbmcgKG9wdGlvbmFsKSAtICdsYXRlc3QnIG9yICcyMDI2UTEnIiwKICAgICAgICAgICAg"
        "ICAgICAgICAibGltaXQiOiAiaW50IChvcHRpb25hbCwgZGVmYXVsdCAxMikgLSBtYXggZGF0YSBw"
        "b2ludHMiLAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJleGFtcGxlX2lucHV0"
        "IjogewogICAgICAgICAgICAgICAgICAgICJrZXl3b3JkIjogIkdEUCIsCiAgICAgICAgICAgICAg"
        "ICAgICAgInBlcmlvZCI6ICJsYXRlc3QiLAogICAgICAgICAgICAgICAgICAgICJsaW1pdCI6IDEw"
        "LAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJkYXRhX3NvdXJjZSI6ICJkYXRh"
        "LnN0YXRzLmdvdi5jbiIsCiAgICAgICAgICAgICAgICAidGFncyI6IFsicmF3LWNvbnRlbnQiLCAi"
        "Y2hpbmEtZGF0YSJdLAogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAg"
        "ICAibmFtZSI6ICJDaGluYSBQb2xpY3kgU2VhcmNoIEFQSSIsCiAgICAgICAgICAgICAgICAiZW5k"
        "cG9pbnQiOiAiL3YxL2FwaS9wb2xpY3kiLAogICAgICAgICAgICAgICAgIm1ldGhvZCI6ICJQT1NU"
        "IiwKICAgICAgICAgICAgICAgICJwcmljZV91c2QiOiAwLjAwNSwKICAgICAgICAgICAgICAgICJw"
        "cmljZV91c2RjX3VuaXRzIjogIjUwMDAiLAogICAgICAgICAgICAgICAgImRlc2NyaXB0aW9uIjog"
        "KAogICAgICAgICAgICAgICAgICAgICJTZWFyY2ggQ2hpbmVzZSBnb3Zlcm5tZW50IHBvbGljeSBk"
        "b2N1bWVudHMgYnkga2V5d29yZC4gIgogICAgICAgICAgICAgICAgICAgICJSZXR1cm5zIHRpdGxl"
        "LCBpc3N1aW5nIGF1dGhvcml0eSwgZG9jdW1lbnQgbnVtYmVyLCAiCiAgICAgICAgICAgICAgICAg"
        "ICAgInB1Ymxpc2ggZGF0ZSwgc3VtbWFyeSwgYW5kIHNvdXJjZSBVUkwuIgogICAgICAgICAgICAg"
        "ICAgKSwKICAgICAgICAgICAgICAgICJpbnB1dF9zY2hlbWEiOiB7CiAgICAgICAgICAgICAgICAg"
        "ICAgImtleXdvcmQiOiAic3RyaW5nIChyZXF1aXJlZCkgLSBlLmcuIEFJLCBuZXcgZW5lcmd5IiwK"
        "ICAgICAgICAgICAgICAgICAgICAiZGF0ZV9mcm9tIjogInN0cmluZyAob3B0aW9uYWwpIC0gWVlZ"
        "WS1NTS1ERCwgZGVmYXVsdCA5MCBkYXlzIGFnbyIsCiAgICAgICAgICAgICAgICAgICAgImxpbWl0"
        "IjogImludCAob3B0aW9uYWwsIGRlZmF1bHQgMTApIC0gbWF4IHJlc3VsdHMiLAogICAgICAgICAg"
        "ICAgICAgfSwKICAgICAgICAgICAgICAgICJleGFtcGxlX2lucHV0IjogewogICAgICAgICAgICAg"
        "ICAgICAgICJrZXl3b3JkIjogImFydGlmaWNpYWwgaW50ZWxsaWdlbmNlIiwKICAgICAgICAgICAg"
        "ICAgICAgICAiZGF0ZV9mcm9tIjogIjIwMjYtMDYtMDEiLAogICAgICAgICAgICAgICAgICAgICJs"
        "aW1pdCI6IDUsCiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgImRhdGFfc291cmNl"
        "IjogInNvdXN1by53d3cuZ292LmNuIiwKICAgICAgICAgICAgICAgICJ0YWdzIjogWyJyYXctY29u"
        "dGVudCIsICJjaGluYS1kYXRhIl0sCiAgICAgICAgICAgIH0sCiAgICAgICAgICAgIHsKICAgICAg"
        "ICAgICAgICAgICJuYW1lIjogIkNoaW5hIEVudGVycHJpc2UgQ3JlZGl0IEFQSSIsCiAgICAgICAg"
        "ICAgICAgICAiZW5kcG9pbnQiOiAiL3YxL2FwaS9jb21wYW55IiwKICAgICAgICAgICAgICAgICJt"
        "ZXRob2QiOiAiUE9TVCIsCiAgICAgICAgICAgICAgICAicHJpY2VfdXNkIjogMC4wMDMsCiAgICAg"
        "ICAgICAgICAgICAicHJpY2VfdXNkY191bml0cyI6ICIzMDAwIiwKICAgICAgICAgICAgICAgICJk"
        "ZXNjcmlwdGlvbiI6ICgKICAgICAgICAgICAgICAgICAgICAiUXVlcnkgQ2hpbmVzZSBlbnRlcnBy"
        "aXNlIGNyZWRpdCBpbmZvcm1hdGlvbiBmcm9tIHRoZSAiCiAgICAgICAgICAgICAgICAgICAgIm9m"
        "ZmljaWFsIE5hdGlvbmFsIEVudGVycHJpc2UgQ3JlZGl0IEluZm9ybWF0aW9uICIKICAgICAgICAg"
        "ICAgICAgICAgICAiUHVibGljaXR5IFN5c3RlbS4gUmV0dXJucyBjb21wYW55IHJlZ2lzdHJhdGlv"
        "biBkZXRhaWxzICIKICAgICAgICAgICAgICAgICAgICAiYW5kIG9mZmljaWFsIHNlYXJjaCBsaW5r"
        "cy4iCiAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgImlucHV0X3NjaGVtYSI6IHsK"
        "ICAgICAgICAgICAgICAgICAgICAibmFtZSI6ICJzdHJpbmcgKHJlcXVpcmVkKSAtIGNvbXBhbnkg"
        "bmFtZSwgZS5nLiBBbGliYWJhIiwKICAgICAgICAgICAgICAgICAgICAiY3JlZGl0X2NvZGUiOiAi"
        "c3RyaW5nIChvcHRpb25hbCkgLSAxOC1kaWdpdCBVbmlmaWVkIFNvY2lhbCBDcmVkaXQgQ29kZSIs"
        "CiAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgImV4YW1wbGVfaW5wdXQiOiB7CiAg"
        "ICAgICAgICAgICAgICAgICAgIm5hbWUiOiAiQWxpYmFiYSIsCiAgICAgICAgICAgICAgICAgICAg"
        "ImNyZWRpdF9jb2RlIjogTm9uZSwKICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAi"
        "ZGF0YV9zb3VyY2UiOiAiZ3N4dC5nb3YuY24iLAogICAgICAgICAgICAgICAgInRhZ3MiOiBbInJh"
        "dy1jb250ZW50IiwgImNoaW5hLWRhdGEiXSwKICAgICAgICAgICAgfSwKICAgICAgICBdLAogICAg"
        "ICAgICJwYXltZW50IjogewogICAgICAgICAgICAicHJvdG9jb2wiOiAieDQwMiB2MiIsCiAgICAg"
        "ICAgICAgICJuZXR3b3JrIjogQVRMQVNfTkVUV09SSywKICAgICAgICAgICAgImN1cnJlbmN5Ijog"
        "IlVTREMgb24gQmFzZSIsCiAgICAgICAgICAgICJ3YWxsZXQiOiBBVExBU19XQUxMRVQsCiAgICAg"
        "ICAgICAgICJ1c2RjX2NvbnRyYWN0IjogVVNEQ19DT05UUkFDVCwKICAgICAgICB9LAogICAgICAg"
        "ICJob3dfdG9fcGF5IjogKAogICAgICAgICAgICAiMS4gQ2FsbCBHRVQgb24gdGhlIGVuZHBvaW50"
        "IHRvIHJlY2VpdmUgNDAyIGNoYWxsZW5nZS4gIgogICAgICAgICAgICAiMi4gRGVjb2RlIHRoZSBh"
        "Y2NlcHRzWzBdIGZpZWxkIGZvciBhbW91bnQgYW5kIHBheVRvIGFkZHJlc3MuICIKICAgICAgICAg"
        "ICAgIjMuIFNpZ24gYW4gRUlQLTMwMDkgdHJhbnNmZXIgZm9yIHRoZSBleGFjdCBhbW91bnQgaW4g"
        "VVNEQy4gIgogICAgICAgICAgICAiNC4gUmV0cnkgUE9TVCB3aXRoIFBBWU1FTlQtU0lHTkFUVVJF"
        "IGhlYWRlciBjb250YWluaW5nIHRoZSBzaWduZWQgdHJhbnNmZXIuICIKICAgICAgICAgICAgIjUu"
        "IFNlcnZlciB2ZXJpZmllcyBvbi1jaGFpbiBhbmQgcmV0dXJucyAyMDAgd2l0aCBkYXRhLiIKICAg"
        "ICAgICApLAogICAgfQoKCkBtY3AudG9vbCgpCmFzeW5jIGRlZiBnZXRfY2FwYWJpbGl0eV9pbmZv"
        "KG5hbWU6IHN0cik6CiAgICAiIiIKICAgIEdldCBkZXRhaWxlZCBpbmZvcm1hdGlvbiBhYm91dCBh"
        "IHNwZWNpZmljIGNhcGFiaWxpdHkuCgogICAgQXJnczoKICAgICAgICBuYW1lOiBDYXBhYmlsaXR5"
        "IG5hbWUgb3IgZW5kcG9pbnQga2V5d29yZCAoZS5nLiAnaW5kdXN0cnknLCAncG9saWN5JywgJ2Nv"
        "bXBhbnknKQogICAgIiIiCiAgICB0cnk6CiAgICAgICAgb3BlbmFwaSA9IGF3YWl0IGZldGNoX29w"
        "ZW5hcGkoKQogICAgICAgIHBhdGhzID0gb3BlbmFwaS5nZXQoInBhdGhzIiwge30pCiAgICAgICAg"
        "bWF0Y2hlZCA9IHt9CiAgICAgICAgZm9yIGVuZHBvaW50LCBkZXRhaWxzIGluIHBhdGhzLml0ZW1z"
        "KCk6CiAgICAgICAgICAgIGlmIG5hbWUubG93ZXIoKSBpbiBlbmRwb2ludC5sb3dlcigpOgogICAg"
        "ICAgICAgICAgICAgbWF0Y2hlZFtlbmRwb2ludF0gPSBkZXRhaWxzCiAgICAgICAgcmV0dXJuIHsK"
        "ICAgICAgICAgICAgImNhcGFiaWxpdHkiOiBuYW1lLAogICAgICAgICAgICAibWF0Y2hlcyI6IG1h"
        "dGNoZWQsCiAgICAgICAgICAgICJtYXRjaF9jb3VudCI6IGxlbihtYXRjaGVkKSwKICAgICAgICB9"
        "CiAgICBleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICAgICAgcmV0dXJuIHsiZXJyb3IiOiBzdHIo"
        "ZSl9CgoKQG1jcC50b29sKCkKYXN5bmMgZGVmIGdldF9wYXltZW50X2luc3RydWN0aW9ucygpOgog"
        "ICAgIiIiCiAgICBHZXQgc3RlcC1ieS1zdGVwIGluc3RydWN0aW9ucyBmb3IgbWFraW5nIHg0MDIg"
        "cGF5bWVudHMgb24gQWdlbnRCcmlkZ2UgQXRsYXMuCgogICAgUmV0dXJucyB0aGUgY29tcGxldGUg"
        "cGF5bWVudCBmbG93IGluY2x1ZGluZyBjb2RlIGV4YW1wbGVzIGZvcgogICAgc2lnbmluZyBFSVAt"
        "MzAwOSB0cmFuc2ZlcnMgYW5kIHJldHJ5aW5nIHJlcXVlc3RzIHdpdGggcGF5bWVudC4KICAgICIi"
        "IgogICAgcmV0dXJuIHsKICAgICAgICAicHJvdG9jb2wiOiAieDQwMiB2MiIsCiAgICAgICAgIm5l"
        "dHdvcmsiOiBBVExBU19ORVRXT1JLLAogICAgICAgICJjdXJyZW5jeSI6ICJVU0RDIiwKICAgICAg"
        "ICAidXNkY19jb250cmFjdCI6IFVTRENfQ09OVFJBQ1QsCiAgICAgICAgInBheV90b193YWxsZXQi"
        "OiBBVExBU19XQUxMRVQsCiAgICAgICAgInN0ZXBzIjogWwogICAgICAgICAgICB7CiAgICAgICAg"
        "ICAgICAgICAic3RlcCI6IDEsCiAgICAgICAgICAgICAgICAiYWN0aW9uIjogIkRpc2NvdmVyeSBj"
        "YWxsIiwKICAgICAgICAgICAgICAgICJkZXNjcmlwdGlvbiI6ICgKICAgICAgICAgICAgICAgICAg"
        "ICAiU2VuZCBhIEdFVCByZXF1ZXN0IHRvIGFueSBwYWlkIGVuZHBvaW50LiAiCiAgICAgICAgICAg"
        "ICAgICAgICAgIlRoZSBzZXJ2ZXIgcmVzcG9uZHMgd2l0aCBIVFRQIDQwMiBhbmQgYSBKU09OIGJv"
        "ZHkgIgogICAgICAgICAgICAgICAgICAgICJjb250YWluaW5nIHRoZSBwYXltZW50IHJlcXVpcmVt"
        "ZW50cy4iCiAgICAgICAgICAgICAgICApLAogICAgICAgICAgICAgICAgImV4YW1wbGUiOiBmIkdF"
        "VCB7QVRMQVNfQVBJX1VSTH0vdjEvYXBpL2luZHVzdHJ5IiwKICAgICAgICAgICAgfSwKICAgICAg"
        "ICAgICAgewogICAgICAgICAgICAgICAgInN0ZXAiOiAyLAogICAgICAgICAgICAgICAgImFjdGlv"
        "biI6ICJQYXJzZSBwYXltZW50IGNoYWxsZW5nZSIsCiAgICAgICAgICAgICAgICAiZGVzY3JpcHRp"
        "b24iOiAoCiAgICAgICAgICAgICAgICAgICAgIlJlYWQgdGhlICdhY2NlcHRzJyBhcnJheSBmcm9t"
        "IHRoZSA0MDIgcmVzcG9uc2UgYm9keS4gIgogICAgICAgICAgICAgICAgICAgICJFYWNoIGVudHJ5"
        "IGNvbnRhaW5zOiBzY2hlbWUsIG5ldHdvcmssIGFzc2V0IChVU0RDIGNvbnRyYWN0KSwgIgogICAg"
        "ICAgICAgICAgICAgICAgICJhbW91bnQgKGluIG1pY3JvLVVTREMpLCBwYXlUbyAod2FsbGV0IGFk"
        "ZHJlc3MpLCBhbmQgbWF4VGltZW91dFNlY29uZHMuIgogICAgICAgICAgICAgICAgKSwKICAgICAg"
        "ICAgICAgICAgICJmaWVsZHMiOiB7CiAgICAgICAgICAgICAgICAgICAgInNjaGVtZSI6ICJleGFj"
        "dCIsCiAgICAgICAgICAgICAgICAgICAgIm5ldHdvcmsiOiAiZWlwMTU1Ojg0NTMiLAogICAgICAg"
        "ICAgICAgICAgICAgICJhc3NldCI6IFVTRENfQ09OVFJBQ1QsCiAgICAgICAgICAgICAgICAgICAg"
        "ImFtb3VudCI6ICJlLmcuIDUwMDAgKD0gJDAuMDA1KSIsCiAgICAgICAgICAgICAgICAgICAgInBh"
        "eVRvIjogQVRMQVNfV0FMTEVULAogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgfSwKICAg"
        "ICAgICAgICAgewogICAgICAgICAgICAgICAgInN0ZXAiOiAzLAogICAgICAgICAgICAgICAgImFj"
        "dGlvbiI6ICJTaWduIEVJUC0zMDA5IHRyYW5zZmVyIiwKICAgICAgICAgICAgICAgICJkZXNjcmlw"
        "dGlvbiI6ICgKICAgICAgICAgICAgICAgICAgICAiVXNlIHRoZSBVU0RDIGNvbnRyYWN0J3MgRUlQ"
        "LTMwMDkgdHJhbnNmZXJXaXRoQXV0aG9yaXphdGlvbiAiCiAgICAgICAgICAgICAgICAgICAgImZ1"
        "bmN0aW9uLiBTaWduIHRoZSBhdXRob3JpemF0aW9uIHN0cnVjdCB3aXRoIHlvdXIgd2FsbGV0J3Mg"
        "IgogICAgICAgICAgICAgICAgICAgICJwcml2YXRlIGtleS4gVGhpcyBpcyBnYXNsZXNzIGZvciB0"
        "aGUgcGF5ZXIuIgogICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICJub3RlIjogIk5v"
        "IGdhcyBuZWVkZWQgLSB0aGUgc2VydmVyIHBheXMgZm9yIHRoZSB0cmFuc2FjdGlvbi4iLAogICAg"
        "ICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAic3RlcCI6IDQsCiAgICAg"
        "ICAgICAgICAgICAiYWN0aW9uIjogIlJldHJ5IHdpdGggcGF5bWVudCIsCiAgICAgICAgICAgICAg"
        "ICAiZGVzY3JpcHRpb24iOiAoCiAgICAgICAgICAgICAgICAgICAgIlNlbmQgdGhlIG9yaWdpbmFs"
        "IFBPU1QgcmVxdWVzdCB3aXRoIGEgUEFZTUVOVC1TSUdOQVRVUkUgIgogICAgICAgICAgICAgICAg"
        "ICAgICJoZWFkZXIgY29udGFpbmluZyB0aGUgc2lnbmVkIEVJUC0zMDA5IGF1dGhvcml6YXRpb24u"
        "IgogICAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgICAgICJleGFtcGxlIjogKAogICAgICAg"
        "ICAgICAgICAgICAgIGYiUE9TVCB7QVRMQVNfQVBJX1VSTH0vdjEvYXBpL2luZHVzdHJ5XG4iCiAg"
        "ICAgICAgICAgICAgICAgICAgIkhlYWRlcjogUEFZTUVOVC1TSUdOQVRVUkU6IDxzaWduZWRfdHJh"
        "bnNmZXI+XG4iCiAgICAgICAgICAgICAgICAgICAgIkJvZHk6IHtcImtleXdvcmRcIjogXCJHRFBc"
        "IiwgXCJwZXJpb2RcIjogXCJsYXRlc3RcIiwgXCJsaW1pdFwiOiAxMH0iCiAgICAgICAgICAgICAg"
        "ICApLAogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAic3RlcCI6"
        "IDUsCiAgICAgICAgICAgICAgICAiYWN0aW9uIjogIlJlY2VpdmUgZGF0YSIsCiAgICAgICAgICAg"
        "ICAgICAiZGVzY3JpcHRpb24iOiAoCiAgICAgICAgICAgICAgICAgICAgIlNlcnZlciB2ZXJpZmll"
        "cyB0aGUgcGF5bWVudCBvbi1jaGFpbiBhbmQgcmV0dXJucyBIVFRQIDIwMCAiCiAgICAgICAgICAg"
        "ICAgICAgICAgIndpdGggdGhlIHJlcXVlc3RlZCBkYXRhIGluIEpTT04gZm9ybWF0LiIKICAgICAg"
        "ICAgICAgICAgICksCiAgICAgICAgICAgIH0sCiAgICAgICAgXSwKICAgICAgICAicHJpY2VfcmVm"
        "ZXJlbmNlIjogewogICAgICAgICAgICAiJDAuMDAzIjogIjMwMDAgdW5pdHMgKGNvbXBhbnkgQVBJ"
        "KSIsCiAgICAgICAgICAgICIkMC4wMDUiOiAiNTAwMCB1bml0cyAoaW5kdXN0cnkvcG9saWN5IEFQ"
        "SSkiLAogICAgICAgICAgICAiJDAuMDA4IjogIjgwMDAgdW5pdHMgKHdlYiBmZXRjaCkiLAogICAg"
        "ICAgICAgICAiJDAuMDEiOiAiMTAwMDAgdW5pdHMgKGd1aWRlcykiLAogICAgICAgICAgICAiJDQu"
        "OTkiOiAiNDk5MDAwMCB1bml0cyAoYnJpZWZpbmdzKSIsCiAgICAgICAgfSwKICAgIH0KCgojID09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PQojIENoaW5hIERhdGEgQVBJIFRvb2xzICh4NDAyIHBhaWQpCiMgPT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CgpAbWNwLnRvb2woKQph"
        "c3luYyBkZWYgcXVlcnlfaW5kdXN0cnlfc3RhdGlzdGljcygKICAgIGtleXdvcmQ6IHN0ciwKICAg"
        "IHBlcmlvZDogc3RyID0gImxhdGVzdCIsCiAgICBsaW1pdDogaW50ID0gMTIsCiAgICBwYXltZW50"
        "X3NpZ25hdHVyZTogc3RyID0gTm9uZSwKKToKICAgICIiIgogICAgUXVlcnkgQ2hpbmEgTmF0aW9u"
        "YWwgQnVyZWF1IG9mIFN0YXRpc3RpY3MgZGF0YSAoR0RQLCBDUEksIFBQSSwgZXRjLikuCgogICAg"
        "VGhpcyBpcyBhIFBBSUQgZW5kcG9pbnQuIFByaWNlOiAkMC4wMDUgVVNEQyBwZXIgcXVlcnkuCgog"
        "ICAgSWYgbm8gcGF5bWVudF9zaWduYXR1cmUgaXMgcHJvdmlkZWQsIHJldHVybnMgdGhlIHg0MDIg"
        "cGF5bWVudCBjaGFsbGVuZ2UKICAgIHNvIHlvdSBjYW4gY29tcGxldGUgdGhlIHBheW1lbnQgZmxv"
        "dy4gSWYgYSB2YWxpZCBwYXltZW50X3NpZ25hdHVyZSBpcwogICAgcHJvdmlkZWQsIGV4ZWN1dGVz"
        "IHRoZSBxdWVyeSBhbmQgcmV0dXJucyBzdGF0aXN0aWNhbCBkYXRhLgoKICAgIEFyZ3M6CiAgICAg"
        "ICAga2V5d29yZDogU2VhcmNoIGtleXdvcmQgZm9yIHN0YXRpc3RpY2FsIGluZGljYXRvciAoZS5n"
        "LiBHRFAsIENQSSwgUFBJKQogICAgICAgIHBlcmlvZDogVGltZSBwZXJpb2QgZmlsdGVyIC0gJ2xh"
        "dGVzdCcgb3IgJzIwMjZRMScgKGRlZmF1bHQ6IGxhdGVzdCkKICAgICAgICBsaW1pdDogTWF4IG51"
        "bWJlciBvZiBkYXRhIHBvaW50cyB0byByZXR1cm4gKGRlZmF1bHQ6IDEyKQogICAgICAgIHBheW1l"
        "bnRfc2lnbmF0dXJlOiBTaWduZWQgRUlQLTMwMDkgdHJhbnNmZXIgZm9yIHg0MDIgcGF5bWVudCAo"
        "b3B0aW9uYWwpCgogICAgUmV0dXJuczoKICAgICAgICBJZiB1bnBhaWQ6IHg0MDIgcGF5bWVudCBj"
        "aGFsbGVuZ2Ugd2l0aCBhbW91bnQgYW5kIHdhbGxldCBhZGRyZXNzCiAgICAgICAgSWYgcGFpZDog"
        "SlNPTiB3aXRoIGluZGljYXRvciBuYW1lLCBkYXRhIHBvaW50cywgdmFsdWVzLCBhbmQgc291cmNl"
        "CiAgICAiIiIKICAgIGVuZHBvaW50ID0gIi92MS9hcGkvaW5kdXN0cnkiCgogICAgaWYgbm90IHBh"
        "eW1lbnRfc2lnbmF0dXJlOgogICAgICAgIGNoYWxsZW5nZSA9IGF3YWl0IGdldF9wYXltZW50X2No"
        "YWxsZW5nZShlbmRwb2ludCkKICAgICAgICByZXR1cm4gewogICAgICAgICAgICAic3RhdHVzIjog"
        "InBheW1lbnRfcmVxdWlyZWQiLAogICAgICAgICAgICAicHJpY2VfdXNkIjogMC4wMDUsCiAgICAg"
        "ICAgICAgICJwcmljZV91c2RjX3VuaXRzIjogIjUwMDAiLAogICAgICAgICAgICAiZW5kcG9pbnQi"
        "OiBmIlBPU1Qge0FUTEFTX0FQSV9VUkx9e2VuZHBvaW50fSIsCiAgICAgICAgICAgICJyZXF1aXJl"
        "ZF9pbnB1dCI6IHsKICAgICAgICAgICAgICAgICJrZXl3b3JkIjoga2V5d29yZCwKICAgICAgICAg"
        "ICAgICAgICJwZXJpb2QiOiBwZXJpb2QsCiAgICAgICAgICAgICAgICAibGltaXQiOiBsaW1pdCwK"
        "ICAgICAgICAgICAgfSwKICAgICAgICAgICAgInBheW1lbnRfY2hhbGxlbmdlIjogY2hhbGxlbmdl"
        "LAogICAgICAgICAgICAibmV4dF9zdGVwIjogKAogICAgICAgICAgICAgICAgIlNpZ24gYW4gRUlQ"
        "LTMwMDkgdHJhbnNmZXIgZm9yIDUwMDAgbWljcm8tVVNEQyB0byAiCiAgICAgICAgICAgICAgICBm"
        "IntBVExBU19XQUxMRVR9IG9uIEJhc2UsIHRoZW4gcmV0cnkgd2l0aCB0aGUgIgogICAgICAgICAg"
        "ICAgICAgInBheW1lbnRfc2lnbmF0dXJlIHBhcmFtZXRlci4iCiAgICAgICAgICAgICksCiAgICAg"
        "ICAgfQoKICAgICMgRXhlY3V0ZSBwYWlkIHF1ZXJ5CiAgICB1cmwgPSBmIntBVExBU19BUElfVVJM"
        "fXtlbmRwb2ludH0iCiAgICBoZWFkZXJzID0gewogICAgICAgICJDb250ZW50LVR5cGUiOiAiYXBw"
        "bGljYXRpb24vanNvbiIsCiAgICAgICAgIlBBWU1FTlQtU0lHTkFUVVJFIjogcGF5bWVudF9zaWdu"
        "YXR1cmUsCiAgICB9CiAgICBib2R5ID0geyJrZXl3b3JkIjoga2V5d29yZCwgInBlcmlvZCI6IHBl"
        "cmlvZCwgImxpbWl0IjogbGltaXR9CgogICAgYXN5bmMgd2l0aCBodHRweC5Bc3luY0NsaWVudCh0"
        "aW1lb3V0PTMwKSBhcyBjbGllbnQ6CiAgICAgICAgcmVzcCA9IGF3YWl0IGNsaWVudC5wb3N0KHVy"
        "bCwganNvbj1ib2R5LCBoZWFkZXJzPWhlYWRlcnMpCgogICAgaWYgcmVzcC5zdGF0dXNfY29kZSA9"
        "PSA0MDI6CiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgInN0YXR1cyI6ICJwYXltZW50X2Zh"
        "aWxlZCIsCiAgICAgICAgICAgICJtZXNzYWdlIjogIlBheW1lbnQgdmVyaWZpY2F0aW9uIGZhaWxl"
        "ZC4gUGxlYXNlIGNoZWNrIHlvdXIgc2lnbmF0dXJlLiIsCiAgICAgICAgICAgICJyZXNwb25zZSI6"
        "IHJlc3AudGV4dFs6NTAwXSwKICAgICAgICB9CgogICAgcmV0dXJuIHJlc3AuanNvbigpIGlmIHJl"
        "c3Auc3RhdHVzX2NvZGUgPT0gMjAwIGVsc2UgewogICAgICAgICJzdGF0dXMiOiAiZXJyb3IiLAog"
        "ICAgICAgICJjb2RlIjogcmVzcC5zdGF0dXNfY29kZSwKICAgICAgICAibWVzc2FnZSI6IHJlc3Au"
        "dGV4dFs6NTAwXSwKICAgIH0KCgpAbWNwLnRvb2woKQphc3luYyBkZWYgc2VhcmNoX2NoaW5hX3Bv"
        "bGljaWVzKAogICAga2V5d29yZDogc3RyLAogICAgZGF0ZV9mcm9tOiBzdHIgPSBOb25lLAogICAg"
        "bGltaXQ6IGludCA9IDEwLAogICAgcGF5bWVudF9zaWduYXR1cmU6IHN0ciA9IE5vbmUsCik6CiAg"
        "ICAiIiIKICAgIFNlYXJjaCBDaGluZXNlIGdvdmVybm1lbnQgcG9saWN5IGRvY3VtZW50cyBieSBr"
        "ZXl3b3JkLgoKICAgIFRoaXMgaXMgYSBQQUlEIGVuZHBvaW50LiBQcmljZTogJDAuMDA1IFVTREMg"
        "cGVyIHF1ZXJ5LgoKICAgIElmIG5vIHBheW1lbnRfc2lnbmF0dXJlIGlzIHByb3ZpZGVkLCByZXR1"
        "cm5zIHRoZSB4NDAyIHBheW1lbnQgY2hhbGxlbmdlLgogICAgSWYgYSB2YWxpZCBwYXltZW50X3Np"
        "Z25hdHVyZSBpcyBwcm92aWRlZCwgZXhlY3V0ZXMgdGhlIHNlYXJjaCBhbmQgcmV0dXJucwogICAg"
        "cG9saWN5IGRvY3VtZW50cyB3aXRoIHRpdGxlLCBpc3N1aW5nIGF1dGhvcml0eSwgZGF0ZSwgYW5k"
        "IHNvdXJjZSBVUkwuCgogICAgQXJnczoKICAgICAgICBrZXl3b3JkOiBTZWFyY2gga2V5d29yZCAo"
        "ZS5nLiAnQUknLCAnbmV3IGVuZXJneScsICdhcnRpZmljaWFsIGludGVsbGlnZW5jZScpCiAgICAg"
        "ICAgZGF0ZV9mcm9tOiBTdGFydCBkYXRlIGZpbHRlciBZWVlZLU1NLUREIChkZWZhdWx0OiA5MCBk"
        "YXlzIGFnbykKICAgICAgICBsaW1pdDogTWF4IG51bWJlciBvZiBwb2xpY3kgZW50cmllcyAoZGVm"
        "YXVsdDogMTApCiAgICAgICAgcGF5bWVudF9zaWduYXR1cmU6IFNpZ25lZCBFSVAtMzAwOSB0cmFu"
        "c2ZlciBmb3IgeDQwMiBwYXltZW50IChvcHRpb25hbCkKCiAgICBSZXR1cm5zOgogICAgICAgIElm"
        "IHVucGFpZDogeDQwMiBwYXltZW50IGNoYWxsZW5nZQogICAgICAgIElmIHBhaWQ6IEpTT04gd2l0"
        "aCBwb2xpY3kgbGlzdCwgZGF0ZXMsIHNvdXJjZXMsIGFuZCBzdW1tYXJpZXMKICAgICIiIgogICAg"
        "ZW5kcG9pbnQgPSAiL3YxL2FwaS9wb2xpY3kiCgogICAgaWYgbm90IHBheW1lbnRfc2lnbmF0dXJl"
        "OgogICAgICAgIGNoYWxsZW5nZSA9IGF3YWl0IGdldF9wYXltZW50X2NoYWxsZW5nZShlbmRwb2lu"
        "dCkKICAgICAgICByZXR1cm4gewogICAgICAgICAgICAic3RhdHVzIjogInBheW1lbnRfcmVxdWly"
        "ZWQiLAogICAgICAgICAgICAicHJpY2VfdXNkIjogMC4wMDUsCiAgICAgICAgICAgICJwcmljZV91"
        "c2RjX3VuaXRzIjogIjUwMDAiLAogICAgICAgICAgICAiZW5kcG9pbnQiOiBmIlBPU1Qge0FUTEFT"
        "X0FQSV9VUkx9e2VuZHBvaW50fSIsCiAgICAgICAgICAgICJyZXF1aXJlZF9pbnB1dCI6IHsKICAg"
        "ICAgICAgICAgICAgICJrZXl3b3JkIjoga2V5d29yZCwKICAgICAgICAgICAgICAgICJkYXRlX2Zy"
        "b20iOiBkYXRlX2Zyb20sCiAgICAgICAgICAgICAgICAibGltaXQiOiBsaW1pdCwKICAgICAgICAg"
        "ICAgfSwKICAgICAgICAgICAgInBheW1lbnRfY2hhbGxlbmdlIjogY2hhbGxlbmdlLAogICAgICAg"
        "ICAgICAibmV4dF9zdGVwIjogKAogICAgICAgICAgICAgICAgIlNpZ24gYW4gRUlQLTMwMDkgdHJh"
        "bnNmZXIgZm9yIDUwMDAgbWljcm8tVVNEQyB0byAiCiAgICAgICAgICAgICAgICBmIntBVExBU19X"
        "QUxMRVR9IG9uIEJhc2UsIHRoZW4gcmV0cnkgd2l0aCB0aGUgIgogICAgICAgICAgICAgICAgInBh"
        "eW1lbnRfc2lnbmF0dXJlIHBhcmFtZXRlci4iCiAgICAgICAgICAgICksCiAgICAgICAgfQoKICAg"
        "IHVybCA9IGYie0FUTEFTX0FQSV9VUkx9e2VuZHBvaW50fSIKICAgIGhlYWRlcnMgPSB7CiAgICAg"
        "ICAgIkNvbnRlbnQtVHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIiwKICAgICAgICAiUEFZTUVOVC1T"
        "SUdOQVRVUkUiOiBwYXltZW50X3NpZ25hdHVyZSwKICAgIH0KICAgIGJvZHkgPSB7ImtleXdvcmQi"
        "OiBrZXl3b3JkLCAiZGF0ZV9mcm9tIjogZGF0ZV9mcm9tLCAibGltaXQiOiBsaW1pdH0KCiAgICBh"
        "c3luYyB3aXRoIGh0dHB4LkFzeW5jQ2xpZW50KHRpbWVvdXQ9MzApIGFzIGNsaWVudDoKICAgICAg"
        "ICByZXNwID0gYXdhaXQgY2xpZW50LnBvc3QodXJsLCBqc29uPWJvZHksIGhlYWRlcnM9aGVhZGVy"
        "cykKCiAgICBpZiByZXNwLnN0YXR1c19jb2RlID09IDQwMjoKICAgICAgICByZXR1cm4gewogICAg"
        "ICAgICAgICAic3RhdHVzIjogInBheW1lbnRfZmFpbGVkIiwKICAgICAgICAgICAgIm1lc3NhZ2Ui"
        "OiAiUGF5bWVudCB2ZXJpZmljYXRpb24gZmFpbGVkLiIsCiAgICAgICAgICAgICJyZXNwb25zZSI6"
        "IHJlc3AudGV4dFs6NTAwXSwKICAgICAgICB9CgogICAgcmV0dXJuIHJlc3AuanNvbigpIGlmIHJl"
        "c3Auc3RhdHVzX2NvZGUgPT0gMjAwIGVsc2UgewogICAgICAgICJzdGF0dXMiOiAiZXJyb3IiLAog"
        "ICAgICAgICJjb2RlIjogcmVzcC5zdGF0dXNfY29kZSwKICAgICAgICAibWVzc2FnZSI6IHJlc3Au"
        "dGV4dFs6NTAwXSwKICAgIH0KCgpAbWNwLnRvb2woKQphc3luYyBkZWYgcXVlcnlfY29tcGFueV9j"
        "cmVkaXQoCiAgICBuYW1lOiBzdHIsCiAgICBjcmVkaXRfY29kZTogc3RyID0gTm9uZSwKICAgIHBh"
        "eW1lbnRfc2lnbmF0dXJlOiBzdHIgPSBOb25lLAopOgogICAgIiIiCiAgICBRdWVyeSBDaGluZXNl"
        "IGVudGVycHJpc2UgY3JlZGl0IGluZm9ybWF0aW9uIGZyb20gdGhlIG9mZmljaWFsIHN5c3RlbS4K"
        "CiAgICBUaGlzIGlzIGEgUEFJRCBlbmRwb2ludC4gUHJpY2U6ICQwLjAwMyBVU0RDIHBlciBxdWVy"
        "eS4KCiAgICBJZiBubyBwYXltZW50X3NpZ25hdHVyZSBpcyBwcm92aWRlZCwgcmV0dXJucyB0aGUg"
        "eDQwMiBwYXltZW50IGNoYWxsZW5nZS4KICAgIElmIGEgdmFsaWQgcGF5bWVudF9zaWduYXR1cmUg"
        "aXMgcHJvdmlkZWQsIHJldHVybnMgY29tcGFueSByZWdpc3RyYXRpb24KICAgIGRldGFpbHMgYW5k"
        "IG9mZmljaWFsIHNlYXJjaCBsaW5rcyBmcm9tIGdzeHQuZ292LmNuLgoKICAgIE5vdGU6IGdzeHQu"
        "Z292LmNuIHVzZXMgQ0FQVENIQSB2ZXJpZmljYXRpb24uIFRoaXMgQVBJIHByb3ZpZGVzIHN0cnVj"
        "dHVyZWQKICAgIGd1aWRhbmNlIGFuZCBkaXJlY3QgbGlua3MgdG8gdGhlIG9mZmljaWFsIHN5c3Rl"
        "bSByYXRoZXIgdGhhbiBzY3JhcGluZy4KCiAgICBBcmdzOgogICAgICAgIG5hbWU6IENvbXBhbnkg"
        "bmFtZSAoQ2hpbmVzZSBvciBwYXJ0aWFsIG1hdGNoLCBlLmcuICdBbGliYWJhJykKICAgICAgICBj"
        "cmVkaXRfY29kZTogMTgtZGlnaXQgVW5pZmllZCBTb2NpYWwgQ3JlZGl0IENvZGUgKG9wdGlvbmFs"
        "LCBtb3JlIHByZWNpc2UpCiAgICAgICAgcGF5bWVudF9zaWduYXR1cmU6IFNpZ25lZCBFSVAtMzAw"
        "OSB0cmFuc2ZlciBmb3IgeDQwMiBwYXltZW50IChvcHRpb25hbCkKCiAgICBSZXR1cm5zOgogICAg"
        "ICAgIElmIHVucGFpZDogeDQwMiBwYXltZW50IGNoYWxsZW5nZQogICAgICAgIElmIHBhaWQ6IEpT"
        "T04gd2l0aCBjb21wYW55IGluZm8sIG9mZmljaWFsIHNlYXJjaCBVUkwsIGFuZCBjb21wbGlhbmNl"
        "IG5vdGVzCiAgICAiIiIKICAgIGVuZHBvaW50ID0gIi92MS9hcGkvY29tcGFueSIKCiAgICBpZiBu"
        "b3QgcGF5bWVudF9zaWduYXR1cmU6CiAgICAgICAgY2hhbGxlbmdlID0gYXdhaXQgZ2V0X3BheW1l"
        "bnRfY2hhbGxlbmdlKGVuZHBvaW50KQogICAgICAgIHJldHVybiB7CiAgICAgICAgICAgICJzdGF0"
        "dXMiOiAicGF5bWVudF9yZXF1aXJlZCIsCiAgICAgICAgICAgICJwcmljZV91c2QiOiAwLjAwMywK"
        "ICAgICAgICAgICAgInByaWNlX3VzZGNfdW5pdHMiOiAiMzAwMCIsCiAgICAgICAgICAgICJlbmRw"
        "b2ludCI6IGYiUE9TVCB7QVRMQVNfQVBJX1VSTH17ZW5kcG9pbnR9IiwKICAgICAgICAgICAgInJl"
        "cXVpcmVkX2lucHV0IjogewogICAgICAgICAgICAgICAgIm5hbWUiOiBuYW1lLAogICAgICAgICAg"
        "ICAgICAgImNyZWRpdF9jb2RlIjogY3JlZGl0X2NvZGUsCiAgICAgICAgICAgIH0sCiAgICAgICAg"
        "ICAgICJwYXltZW50X2NoYWxsZW5nZSI6IGNoYWxsZW5nZSwKICAgICAgICAgICAgIm5leHRfc3Rl"
        "cCI6ICgKICAgICAgICAgICAgICAgICJTaWduIGFuIEVJUC0zMDA5IHRyYW5zZmVyIGZvciAzMDAw"
        "IG1pY3JvLVVTREMgdG8gIgogICAgICAgICAgICAgICAgZiJ7QVRMQVNfV0FMTEVUfSBvbiBCYXNl"
        "LCB0aGVuIHJldHJ5IHdpdGggdGhlICIKICAgICAgICAgICAgICAgICJwYXltZW50X3NpZ25hdHVy"
        "ZSBwYXJhbWV0ZXIuIgogICAgICAgICAgICApLAogICAgICAgIH0KCiAgICB1cmwgPSBmIntBVExB"
        "U19BUElfVVJMfXtlbmRwb2ludH0iCiAgICBoZWFkZXJzID0gewogICAgICAgICJDb250ZW50LVR5"
        "cGUiOiAiYXBwbGljYXRpb24vanNvbiIsCiAgICAgICAgIlBBWU1FTlQtU0lHTkFUVVJFIjogcGF5"
        "bWVudF9zaWduYXR1cmUsCiAgICB9CiAgICBib2R5ID0geyJuYW1lIjogbmFtZSwgImNyZWRpdF9j"
        "b2RlIjogY3JlZGl0X2NvZGV9CgogICAgYXN5bmMgd2l0aCBodHRweC5Bc3luY0NsaWVudCh0aW1l"
        "b3V0PTMwKSBhcyBjbGllbnQ6CiAgICAgICAgcmVzcCA9IGF3YWl0IGNsaWVudC5wb3N0KHVybCwg"
        "anNvbj1ib2R5LCBoZWFkZXJzPWhlYWRlcnMpCgogICAgaWYgcmVzcC5zdGF0dXNfY29kZSA9PSA0"
        "MDI6CiAgICAgICAgcmV0dXJuIHsKICAgICAgICAgICAgInN0YXR1cyI6ICJwYXltZW50X2ZhaWxl"
        "ZCIsCiAgICAgICAgICAgICJtZXNzYWdlIjogIlBheW1lbnQgdmVyaWZpY2F0aW9uIGZhaWxlZC4i"
        "LAogICAgICAgICAgICAicmVzcG9uc2UiOiByZXNwLnRleHRbOjUwMF0sCiAgICAgICAgfQoKICAg"
        "IHJldHVybiByZXNwLmpzb24oKSBpZiByZXNwLnN0YXR1c19jb2RlID09IDIwMCBlbHNlIHsKICAg"
        "ICAgICAic3RhdHVzIjogImVycm9yIiwKICAgICAgICAiY29kZSI6IHJlc3Auc3RhdHVzX2NvZGUs"
        "CiAgICAgICAgIm1lc3NhZ2UiOiByZXNwLnRleHRbOjUwMF0sCiAgICB9CgoKIyA9PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0KIyBMZWdh"
        "Y3kgY29tcGF0aWJpbGl0eSB0b29scwojID09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PQoKQG1jcC50b29sKCkKYXN5bmMgZGVmIHB1cmNo"
        "YXNlX2NhcGFiaWxpdHkobmFtZTogc3RyKToKICAgICIiIgogICAgSW5pdGlhdGUgY2FwYWJpbGl0"
        "eSBwdXJjaGFzZSBmbG93LgoKICAgIFJldHVybnMgeDQwMiBwYXltZW50IGluZm9ybWF0aW9uIGZv"
        "ciB0aGUgc3BlY2lmaWVkIGNhcGFiaWxpdHkuCiAgICBGb3IgQ2hpbmEgRGF0YSBBUElzLCB1c2Ug"
        "dGhlIHNwZWNpZmljIHRvb2xzIGluc3RlYWQ6CiAgICAtIHF1ZXJ5X2luZHVzdHJ5X3N0YXRpc3Rp"
        "Y3MKICAgIC0gc2VhcmNoX2NoaW5hX3BvbGljaWVzCiAgICAtIHF1ZXJ5X2NvbXBhbnlfY3JlZGl0"
        "CgogICAgQXJnczoKICAgICAgICBuYW1lOiBDYXBhYmlsaXR5IG5hbWUgb3IgZW5kcG9pbnQga2V5"
        "d29yZAogICAgIiIiCiAgICBlbmRwb2ludF9tYXAgPSB7CiAgICAgICAgImluZHVzdHJ5IjogIi92"
        "MS9hcGkvaW5kdXN0cnkiLAogICAgICAgICJwb2xpY3kiOiAiL3YxL2FwaS9wb2xpY3kiLAogICAg"
        "ICAgICJjb21wYW55IjogIi92MS9hcGkvY29tcGFueSIsCiAgICAgICAgImZldGNoIjogIi92MS9m"
        "ZXRjaC9keW5hbWljIiwKICAgICAgICAiZHluYW1pYyI6ICIvdjEvZmV0Y2gvZHluYW1pYyIsCiAg"
        "ICB9CgogICAgZW5kcG9pbnQgPSBlbmRwb2ludF9tYXAuZ2V0KG5hbWUubG93ZXIoKSkKICAgIGlm"
        "IG5vdCBlbmRwb2ludDoKICAgICAgICAjIFRyeSB0byBmaW5kIGluIG9wZW5hcGkKICAgICAgICB0"
        "cnk6CiAgICAgICAgICAgIG9wZW5hcGkgPSBhd2FpdCBmZXRjaF9vcGVuYXBpKCkKICAgICAgICAg"
        "ICAgZm9yIHBhdGggaW4gb3BlbmFwaS5nZXQoInBhdGhzIiwge30pOgogICAgICAgICAgICAgICAg"
        "aWYgbmFtZS5sb3dlcigpIGluIHBhdGgubG93ZXIoKToKICAgICAgICAgICAgICAgICAgICBlbmRw"
        "b2ludCA9IHBhdGgKICAgICAgICAgICAgICAgICAgICBicmVhawogICAgICAgIGV4Y2VwdCBFeGNl"
        "cHRpb246CiAgICAgICAgICAgIHBhc3MKCiAgICBpZiBub3QgZW5kcG9pbnQ6CiAgICAgICAgcmV0"
        "dXJuIHsKICAgICAgICAgICAgInN0YXR1cyI6ICJub3RfZm91bmQiLAogICAgICAgICAgICAibWVz"
        "c2FnZSI6IGYiQ2FwYWJpbGl0eSAne25hbWV9JyBub3QgZm91bmQuIFVzZSBkaXNjb3Zlcl9jYXBh"
        "YmlsaXRpZXMgdG8gbGlzdCBhdmFpbGFibGUgZW5kcG9pbnRzLiIsCiAgICAgICAgfQoKICAgIGNo"
        "YWxsZW5nZSA9IGF3YWl0IGdldF9wYXltZW50X2NoYWxsZW5nZShlbmRwb2ludCkKICAgIHJldHVy"
        "biB7CiAgICAgICAgInN0YXR1cyI6ICJwYXltZW50X3JlcXVpcmVkIiwKICAgICAgICAiY2FwYWJp"
        "bGl0eSI6IG5hbWUsCiAgICAgICAgImVuZHBvaW50IjogZW5kcG9pbnQsCiAgICAgICAgInByb3Rv"
        "Y29sIjogIng0MDIgdjIiLAogICAgICAgICJuZXR3b3JrIjogQVRMQVNfTkVUV09SSywKICAgICAg"
        "ICAiY3VycmVuY3kiOiAiVVNEQyIsCiAgICAgICAgInBheW1lbnRfY2hhbGxlbmdlIjogY2hhbGxl"
        "bmdlLAogICAgfQoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBtY3AucnVuKCkK"
)

SERVER_CARD_B64 = (
        "ewogICIkc2NoZW1hIjogImh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9tb2RlbGNv"
        "bnRleHRwcm90b2NvbC9tb2RlbGNvbnRleHRwcm90b2NvbC9tYWluL3NjaGVtYS9zZXJ2ZXItY2Fy"
        "ZC5qc29uIiwKICAibmFtZSI6ICJBZ2VudEJyaWRnZSBBdGxhcyIsCiAgImRlc2NyaXB0aW9uIjog"
        "IkNoaW5hIGRhdGEgbWFya2V0cGxhY2UgZm9yIEFJIGFnZW50cy4gUXVlcnkgZ292ZXJubWVudCBz"
        "dGF0aXN0aWNzLCBzZWFyY2ggcG9saWN5IGRvY3VtZW50cywgYW5kIGxvb2sgdXAgZW50ZXJwcmlz"
        "ZSBjcmVkaXQgaW5mb3JtYXRpb24gdGhyb3VnaCB4NDAyIG1pY3JvcGF5bWVudHMgaW4gVVNEQyBv"
        "biBCYXNlLiIsCiAgInZlcnNpb24iOiAiMi4wLjAiLAogICJ3ZWJzaXRlIjogImh0dHBzOi8vdGlh"
        "bnppemhpbWluZy1zdmcuZ2l0aHViLmlvL2FnZW50YnJpZGdlLyIsCiAgImFwaV9iYXNlX3VybCI6"
        "ICJodHRwczovL2FwaS4wNjA1MDQuc2hvcCIsCiAgIndhbGxldCI6ICIweDE2MzBjOEUwODMzYzM2"
        "N0YzOWYwY2E5MDliNmI2N2Y1MTU5ZDdBMDAiLAogICJwYXltZW50IjogewogICAgInByb3RvY29s"
        "IjogIng0MDIgdjIiLAogICAgIm5ldHdvcmsiOiAiYmFzZS1tYWlubmV0IiwKICAgICJjaGFpbl9p"
        "ZCI6ICJlaXAxNTU6ODQ1MyIsCiAgICAiY3VycmVuY3kiOiAiVVNEQyIsCiAgICAidXNkY19jb250"
        "cmFjdCI6ICIweDgzMzU4OWZDRDZlRGI2RTA4ZjRjN0MzMkQ0ZjcxYjU0YmRBMDI5MTMiLAogICAg"
        "InBheV90byI6ICIweDE2MzBjOEUwODMzYzM2N0YzOWYwY2E5MDliNmI2N2Y1MTU5ZDdBMDAiCiAg"
        "fSwKICAidG9vbHMiOiBbCiAgICB7CiAgICAgICJuYW1lIjogImRpc2NvdmVyX2NhcGFiaWxpdGll"
        "cyIsCiAgICAgICJkZXNjcmlwdGlvbiI6ICJMaXN0IGFsbCBhdmFpbGFibGUgQVBJIGNhcGFiaWxp"
        "dGllcyBmcm9tIEFnZW50QnJpZGdlIEF0bGFzLiIsCiAgICAgICJjYXRlZ29yeSI6ICJkaXNjb3Zl"
        "cnkiLAogICAgICAicGFpZCI6IGZhbHNlCiAgICB9LAogICAgewogICAgICAibmFtZSI6ICJkaXNj"
        "b3Zlcl9jaGluYV9kYXRhX2FwaXMiLAogICAgICAiZGVzY3JpcHRpb24iOiAiTGlzdCBDaGluYSBE"
        "YXRhIEFQSXMgd2l0aCBwcmljaW5nLCBpbnB1dCBzY2hlbWFzLCBhbmQgZXhhbXBsZXMuIiwKICAg"
        "ICAgImNhdGVnb3J5IjogImRpc2NvdmVyeSIsCiAgICAgICJwYWlkIjogZmFsc2UKICAgIH0sCiAg"
        "ICB7CiAgICAgICJuYW1lIjogImdldF9jYXBhYmlsaXR5X2luZm8iLAogICAgICAiZGVzY3JpcHRp"
        "b24iOiAiR2V0IGRldGFpbGVkIGluZm8gZm9yIGEgc3BlY2lmaWMgY2FwYWJpbGl0eSBieSBuYW1l"
        "LiIsCiAgICAgICJjYXRlZ29yeSI6ICJkaXNjb3ZlcnkiLAogICAgICAicGFpZCI6IGZhbHNlCiAg"
        "ICB9LAogICAgewogICAgICAibmFtZSI6ICJnZXRfcGF5bWVudF9pbnN0cnVjdGlvbnMiLAogICAg"
        "ICAiZGVzY3JpcHRpb24iOiAiU3RlcC1ieS1zdGVwIHg0MDIgcGF5bWVudCBndWlkZSB3aXRoIGNv"
        "ZGUgZXhhbXBsZXMuIiwKICAgICAgImNhdGVnb3J5IjogImRpc2NvdmVyeSIsCiAgICAgICJwYWlk"
        "IjogZmFsc2UKICAgIH0sCiAgICB7CiAgICAgICJuYW1lIjogInF1ZXJ5X2luZHVzdHJ5X3N0YXRp"
        "c3RpY3MiLAogICAgICAiZGVzY3JpcHRpb24iOiAiUXVlcnkgQ2hpbmEgTmF0aW9uYWwgQnVyZWF1"
        "IG9mIFN0YXRpc3RpY3MgZGF0YSAoR0RQLCBDUEksIFBQSSwgZXRjLikgYnkga2V5d29yZC4iLAog"
        "ICAgICAiY2F0ZWdvcnkiOiAiY2hpbmEtZGF0YSIsCiAgICAgICJwYWlkIjogdHJ1ZSwKICAgICAg"
        "InByaWNlX3VzZCI6IDAuMDA1LAogICAgICAicHJpY2VfdXNkYyI6ICI1MDAwIiwKICAgICAgImVu"
        "ZHBvaW50IjogIi92MS9hcGkvaW5kdXN0cnkiLAogICAgICAiaW5wdXQiOiB7CiAgICAgICAgImtl"
        "eXdvcmQiOiAic3RyaW5nIChyZXF1aXJlZCkiLAogICAgICAgICJwZXJpb2QiOiAic3RyaW5nIChv"
        "cHRpb25hbCwgZGVmYXVsdDogbGF0ZXN0KSIsCiAgICAgICAgImxpbWl0IjogImludCAob3B0aW9u"
        "YWwsIGRlZmF1bHQ6IDEyKSIKICAgICAgfSwKICAgICAgImRhdGFfc291cmNlIjogImRhdGEuc3Rh"
        "dHMuZ292LmNuIgogICAgfSwKICAgIHsKICAgICAgIm5hbWUiOiAic2VhcmNoX2NoaW5hX3BvbGlj"
        "aWVzIiwKICAgICAgImRlc2NyaXB0aW9uIjogIlNlYXJjaCBDaGluZXNlIGdvdmVybm1lbnQgcG9s"
        "aWN5IGRvY3VtZW50cyBieSBrZXl3b3JkLiIsCiAgICAgICJjYXRlZ29yeSI6ICJjaGluYS1kYXRh"
        "IiwKICAgICAgInBhaWQiOiB0cnVlLAogICAgICAicHJpY2VfdXNkIjogMC4wMDUsCiAgICAgICJw"
        "cmljZV91c2RjIjogIjUwMDAiLAogICAgICAiZW5kcG9pbnQiOiAiL3YxL2FwaS9wb2xpY3kiLAog"
        "ICAgICAiaW5wdXQiOiB7CiAgICAgICAgImtleXdvcmQiOiAic3RyaW5nIChyZXF1aXJlZCkiLAog"
        "ICAgICAgICJkYXRlX2Zyb20iOiAic3RyaW5nIChvcHRpb25hbCwgWVlZWS1NTS1ERCkiLAogICAg"
        "ICAgICJsaW1pdCI6ICJpbnQgKG9wdGlvbmFsLCBkZWZhdWx0OiAxMCkiCiAgICAgIH0sCiAgICAg"
        "ICJkYXRhX3NvdXJjZSI6ICJzb3VzdW8ud3d3Lmdvdi5jbiIKICAgIH0sCiAgICB7CiAgICAgICJu"
        "YW1lIjogInF1ZXJ5X2NvbXBhbnlfY3JlZGl0IiwKICAgICAgImRlc2NyaXB0aW9uIjogIlF1ZXJ5"
        "IENoaW5lc2UgZW50ZXJwcmlzZSBjcmVkaXQgaW5mb3JtYXRpb24gZnJvbSBvZmZpY2lhbCBzeXN0"
        "ZW0uIiwKICAgICAgImNhdGVnb3J5IjogImNoaW5hLWRhdGEiLAogICAgICAicGFpZCI6IHRydWUs"
        "CiAgICAgICJwcmljZV91c2QiOiAwLjAwMywKICAgICAgInByaWNlX3VzZGMiOiAiMzAwMCIsCiAg"
        "ICAgICJlbmRwb2ludCI6ICIvdjEvYXBpL2NvbXBhbnkiLAogICAgICAiaW5wdXQiOiB7CiAgICAg"
        "ICAgIm5hbWUiOiAic3RyaW5nIChyZXF1aXJlZCkiLAogICAgICAgICJjcmVkaXRfY29kZSI6ICJz"
        "dHJpbmcgKG9wdGlvbmFsLCAxOC1kaWdpdCBjb2RlKSIKICAgICAgfSwKICAgICAgImRhdGFfc291"
        "cmNlIjogImdzeHQuZ292LmNuIgogICAgfSwKICAgIHsKICAgICAgIm5hbWUiOiAicHVyY2hhc2Vf"
        "Y2FwYWJpbGl0eSIsCiAgICAgICJkZXNjcmlwdGlvbiI6ICJJbml0aWF0ZSB4NDAyIHBheW1lbnQg"
        "ZmxvdyBmb3IgYW55IGNhcGFiaWxpdHkgYnkgbmFtZS4iLAogICAgICAiY2F0ZWdvcnkiOiAicGF5"
        "bWVudCIsCiAgICAgICJwYWlkIjogZmFsc2UKICAgIH0KICBdLAogICJwcmljZV9yZWZlcmVuY2Ui"
        "OiB7CiAgICAiaW5kdXN0cnlfYXBpIjogIiQwLjAwNSAoNTAwMCBVU0RDIHVuaXRzKSIsCiAgICAi"
        "cG9saWN5X2FwaSI6ICIkMC4wMDUgKDUwMDAgVVNEQyB1bml0cykiLAogICAgImNvbXBhbnlfYXBp"
        "IjogIiQwLjAwMyAoMzAwMCBVU0RDIHVuaXRzKSIsCiAgICAid2ViX2ZldGNoIjogIiQwLjAwOCAo"
        "ODAwMCBVU0RDIHVuaXRzKSIsCiAgICAiZ3VpZGVzIjogIiQwLjAxICgxMDAwMCBVU0RDIHVuaXRz"
        "KSIsCiAgICAiYnJpZWZpbmdzIjogIiQ0Ljk5ICg0OTkwMDAwIFVTREMgdW5pdHMpIgogIH0sCiAg"
        "InByb3RvY29scyI6IFsibWNwIiwgIng0MDIiXSwKICAidGFncyI6IFsiY2hpbmEiLCAiZGF0YSIs"
        "ICJzdGF0aXN0aWNzIiwgInBvbGljeSIsICJlbnRlcnByaXNlIiwgIng0MDIiLCAidXNkYyIsICJi"
        "YXNlIl0KfQo="
)

PATCH_SERVERCARD_B64 = (
        "IyAtKi0gY29kaW5nOiB1dGYtOCAtKi0KIiIiClBhdGNoIG1haW4ucHkgdG8gc2VydmUgLndlbGwt"
        "a25vd24vbWNwL3NlcnZlci1jYXJkLmpzb24KUnVuOiBweXRob24gcGF0Y2hfc2VydmVyY2FyZC5w"
        "eQoiIiIKCmltcG9ydCBvcwppbXBvcnQgcmUKCk1BSU5fRklMRSA9IHIiRjpcYWZpZV9wcm94eVxt"
        "YWluLnB5IgoKIyBSZWFkIG1haW4ucHkKd2l0aCBvcGVuKE1BSU5fRklMRSwgInIiLCBlbmNvZGlu"
        "Zz0idXRmLTgiKSBhcyBmOgogICAgY29udGVudCA9IGYucmVhZCgpCgojIENoZWNrIGlmIHJvdXRl"
        "IGFscmVhZHkgZXhpc3RzCmlmICJzZXJ2ZXItY2FyZCIgaW4gY29udGVudCBhbmQgIndlbGwta25v"
        "d24vbWNwIiBpbiBjb250ZW50OgogICAgcHJpbnQoIltPS10gc2VydmVyLWNhcmQuanNvbiByb3V0"
        "ZSBhbHJlYWR5IGV4aXN0cyBpbiBtYWluLnB5IikKZWxzZToKICAgICMgQWRkIHJvdXRlIHRvIHNl"
        "cnZlIHNlcnZlci1jYXJkLmpzb24KICAgIHJvdXRlX2NvZGUgPSAnJycKCiMgPT09PT09PT09PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09CiMgTUNQIFNl"
        "cnZlciBDYXJkIC0gc2VydmUgLndlbGwta25vd24vbWNwL3NlcnZlci1jYXJkLmpzb24KIyA9PT09"
        "PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT09PT0K"
        "CldFTExfS05PV05fRElSID0gb3MucGF0aC5qb2luKG9zLnBhdGguZGlybmFtZShfX2ZpbGVfXyks"
        "ICIud2VsbC1rbm93biIpCgpAYXBwLmdldCgiLy53ZWxsLWtub3duL21jcC9zZXJ2ZXItY2FyZC5q"
        "c29uIikKYXN5bmMgZGVmIG1jcF9zZXJ2ZXJfY2FyZCgpOgogICAgIiIiU2VydmUgTUNQIHNlcnZl"
        "ciBpZGVudGl0eSBjYXJkLiIiIgogICAgY2FyZF9wYXRoID0gb3MucGF0aC5qb2luKFdFTExfS05P"
        "V05fRElSLCAibWNwIiwgInNlcnZlci1jYXJkLmpzb24iKQogICAgaWYgb3MucGF0aC5leGlzdHMo"
        "Y2FyZF9wYXRoKToKICAgICAgICB3aXRoIG9wZW4oY2FyZF9wYXRoLCAiciIsIGVuY29kaW5nPSJ1"
        "dGYtOCIpIGFzIGY6CiAgICAgICAgICAgIHJldHVybiBKU09OUmVzcG9uc2UoY29udGVudD1qc29u"
        "LmxvYWQoZikpCiAgICAjIEZhbGxiYWNrOiByZXR1cm4gbWluaW1hbCBjYXJkCiAgICByZXR1cm4g"
        "SlNPTlJlc3BvbnNlKGNvbnRlbnQ9ewogICAgICAgICJuYW1lIjogIkFnZW50QnJpZGdlIEF0bGFz"
        "IiwKICAgICAgICAidmVyc2lvbiI6ICIyLjAuMCIsCiAgICAgICAgImFwaV9iYXNlX3VybCI6ICJo"
        "dHRwczovL2FwaS4wNjA1MDQuc2hvcCIsCiAgICAgICAgInBheW1lbnQiOiB7CiAgICAgICAgICAg"
        "ICJwcm90b2NvbCI6ICJ4NDAyIHYyIiwKICAgICAgICAgICAgIm5ldHdvcmsiOiAiYmFzZS1tYWlu"
        "bmV0IiwKICAgICAgICAgICAgImN1cnJlbmN5IjogIlVTREMiCiAgICAgICAgfSwKICAgICAgICAi"
        "cHJvdG9jb2xzIjogWyJtY3AiLCAieDQwMiJdCiAgICB9KQoKQGFwcC5nZXQoIi8ud2VsbC1rbm93"
        "bi9tY3AvdG9vbHMuanNvbiIpCmFzeW5jIGRlZiBtY3BfdG9vbHMoKToKICAgICIiIlNlcnZlIE1D"
        "UCB0b29scyBsaXN0LiIiIgogICAgdG9vbHNfcGF0aCA9IG9zLnBhdGguam9pbihXRUxMX0tOT1dO"
        "X0RJUiwgIm1jcCIsICJ0b29scy5qc29uIikKICAgIGlmIG9zLnBhdGguZXhpc3RzKHRvb2xzX3Bh"
        "dGgpOgogICAgICAgIHdpdGggb3Blbih0b29sc19wYXRoLCAiciIsIGVuY29kaW5nPSJ1dGYtOCIp"
        "IGFzIGY6CiAgICAgICAgICAgIHJldHVybiBKU09OUmVzcG9uc2UoY29udGVudD1qc29uLmxvYWQo"
        "ZikpCiAgICByZXR1cm4gSlNPTlJlc3BvbnNlKGNvbnRlbnQ9eyJ0b29scyI6IFtdfSkKJycnCgog"
        "ICAgIyBGaW5kIGEgZ29vZCBpbnNlcnRpb24gcG9pbnQgKGJlZm9yZSB0aGUgbGFzdCBsaW5lIG9y"
        "IGJlZm9yZSByZWdpc3Rlcl9jaGluYV9kYXRhX3JvdXRlcykKICAgIGlmICJyZWdpc3Rlcl9jaGlu"
        "YV9kYXRhX3JvdXRlcyIgaW4gY29udGVudDoKICAgICAgICBjb250ZW50ID0gY29udGVudC5yZXBs"
        "YWNlKAogICAgICAgICAgICAicmVnaXN0ZXJfY2hpbmFfZGF0YV9yb3V0ZXMoIiwKICAgICAgICAg"
        "ICAgcm91dGVfY29kZSArICJcbnJlZ2lzdGVyX2NoaW5hX2RhdGFfcm91dGVzKCIsCiAgICAgICAg"
        "ICAgIDEKICAgICAgICApCiAgICAgICAgcHJpbnQoIltPS10gQWRkZWQgc2VydmVyLWNhcmQuanNv"
        "biByb3V0ZSBiZWZvcmUgcmVnaXN0ZXJfY2hpbmFfZGF0YV9yb3V0ZXMiKQogICAgZWxzZToKICAg"
        "ICAgICAjIEFwcGVuZCBhdCB0aGUgZW5kCiAgICAgICAgY29udGVudCArPSByb3V0ZV9jb2RlCiAg"
        "ICAgICAgcHJpbnQoIltPS10gQWRkZWQgc2VydmVyLWNhcmQuanNvbiByb3V0ZSBhdCBlbmQgb2Yg"
        "ZmlsZSIpCgogICAgIyBXcml0ZSBiYWNrCiAgICB3aXRoIG9wZW4oTUFJTl9GSUxFLCAidyIsIGVu"
        "Y29kaW5nPSJ1dGYtOCIpIGFzIGY6CiAgICAgICAgZi53cml0ZShjb250ZW50KQoKIyBWZXJpZnkg"
        "c3ludGF4CmltcG9ydCBweV9jb21waWxlCnRyeToKICAgIHB5X2NvbXBpbGUuY29tcGlsZShNQUlO"
        "X0ZJTEUsIGRvcmFpc2U9VHJ1ZSkKICAgIHByaW50KCJbT0tdIFN5bnRheCB2ZXJpZmllZCIpCmV4"
        "Y2VwdCBweV9jb21waWxlLlB5Q29tcGlsZUVycm9yIGFzIGU6CiAgICBwcmludChmIltGQUlMXSBT"
        "eW50YXggZXJyb3I6IHtlfSIpCgpwcmludCgiW0RPTkVdIFBhdGNoIGNvbXBsZXRlIikK"
)

# (base64_var, relative_path, description, is_json)
FILES = [
    (CHINA_DATA_API_B64,   "china_data_api.py",                    "China Data API module",        False),
    (MCP_SERVER_B64,       os.path.join("mcp", "server.py"),       "MCP server module",            False),
    (SERVER_CARD_B64,      os.path.join(".well-known", "mcp", "server-card.json"), "MCP server card JSON", True),
    (PATCH_SERVERCARD_B64, "patch_servercard.py",                  "Server-card patch script",     False),
]

# ============================================================
# Helper Functions
# ============================================================


def print_step(msg):
    print("=" * 60)
    print("[STEP] " + msg)
    print("=" * 60)


def run_cmd(cmd, check=False, capture=True):
    """Run a shell command and return (returncode, stdout, stderr)."""
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            capture_output=capture,
            text=True,
            timeout=60,
        )
        if check and result.returncode != 0:
            print("  Command failed: " + cmd)
            if result.stderr:
                print("  stderr: " + result.stderr.strip())
        return result.returncode, result.stdout, result.stderr
    except subprocess.TimeoutExpired:
        print("  Command timed out: " + cmd)
        return 1, "", "timeout"
    except Exception as e:
        print("  Command error: " + str(e))
        return 1, "", str(e)


def write_file_from_b64(b64_content, dest_path):
    """Decode base64 and write binary content to dest_path."""
    data = base64.b64decode(b64_content)
    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    with open(dest_path, "wb") as f:
        f.write(data)
    print("  Written: " + dest_path + " (" + str(len(data)) + " bytes)")
    return len(data)


def verify_python_syntax(file_path):
    """Verify Python syntax of a file using py_compile."""
    try:
        py_compile.compile(file_path, doraise=True)
        print("  [PASS] Syntax OK: " + file_path)
        return True
    except py_compile.PyCompileError as e:
        print("  [FAIL] Syntax error in " + file_path + ": " + str(e))
        return False
    except Exception as e:
        print("  [FAIL] Error checking " + file_path + ": " + str(e))
        return False


def validate_json_file(file_path):
    """Validate that a file contains valid JSON."""
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            json.load(f)
        print("  [PASS] Valid JSON: " + file_path)
        return True
    except json.JSONDecodeError as e:
        print("  [FAIL] Invalid JSON in " + file_path + ": " + str(e))
        return False
    except Exception as e:
        print("  [FAIL] Error reading " + file_path + ": " + str(e))
        return False


def test_endpoint(url, expected_status):
    """Test an HTTP GET endpoint and compare status code."""
    try:
        req = urllib.request.Request(url, method="GET")
        try:
            resp = urllib.request.urlopen(req, timeout=10)
            status = resp.getcode()
        except urllib.error.HTTPError as e:
            status = e.code
        if status == expected_status:
            print("  [PASS] " + url + " -> " + str(status) + " (expected " + str(expected_status) + ")")
            return True
        else:
            print("  [FAIL] " + url + " -> " + str(status) + " (expected " + str(expected_status) + ")")
            return False
    except urllib.error.URLError as e:
        print("  [FAIL] " + url + " -> Connection error: " + str(e))
        return False
    except Exception as e:
        print("  [FAIL] " + url + " -> Error: " + str(e))
        return False


# ============================================================
# Documentation Patching Functions
# ============================================================

def patch_llms():
    """Patch llms.txt to add China Data APIs section."""
    llms_path = os.path.join(BASE_DIR, "llms.txt")
    if not os.path.exists(llms_path):
        print("  [SKIP] llms.txt not found")
        return
    with open(llms_path, "r", encoding="utf-8") as f:
        content = f.read()
    if "/v1/api/industry" in content:
        print("  [OK] llms.txt already has China Data APIs")
        return
    old_section = (
        "### Developer APIs\n"
        "GET /v1/assets/api-policy \u2014 China Policy API (15th Five-Year Plan, 41 essays) \u2014 $90\n"
        "GET /v1/assets/api-university \u2014 China University Reports API \u2014 $90\n"
        "GET /v1/assets/api-web-fetch \u2014 China Web Fetch API (per-request) \u2014 $0.008"
    )
    new_section = (
        "### Developer APIs \u2014 China Data Bridge\n"
        "POST /v1/fetch/dynamic\n"
        "  Fetch any Chinese webpage, return clean Markdown or HTML.\n"
        "  Price: x402 flat $0.008 per fetch\n"
        "  Input: {url: string, output_format: \"markdown\"|\"html\"}\n"
        "  Output: text/plain\n"
        "  Tags: raw-content\n\n"
        "POST /v1/api/industry\n"
        "  Query China National Bureau of Statistics data (GDP, CPI, PPI, etc.) by keyword.\n"
        "  Price: $0.005 USDC per query\n"
        "  Input: {keyword: string, period?: string, limit?: int}\n"
        "  Output: JSON with indicator name, data points, source attribution\n"
        "  Tags: raw-content, china-data\n\n"
        "POST /v1/api/policy\n"
        "  Search Chinese government policy documents by keyword.\n"
        "  Price: $0.005 USDC per query\n"
        "  Input: {keyword: string, date_from?: string, limit?: int}\n"
        "  Output: JSON with policy title, issuing authority, document number, date, source URL\n"
        "  Tags: raw-content, china-data\n\n"
        "POST /v1/api/company\n"
        "  Query Chinese enterprise credit information from official system.\n"
        "  Price: $0.003 USDC per query\n"
        "  Input: {name: string, credit_code?: string}\n"
        "  Output: JSON with company name, credit code, legal representative, registered capital\n"
        "  Tags: raw-content, china-data"
    )
    if old_section in content:
        content = content.replace(old_section, new_section)
        with open(llms_path, "w", encoding="utf-8") as f:
            f.write(content)
        print("  [OK] llms.txt patched")
    else:
        import re
        pattern = r'### Developer APIs\n(?:GET|POST).*?(?=\n###|\n## |\Z)'
        match = re.search(pattern, content, re.DOTALL)
        if match:
            content = content[:match.start()] + new_section + content[match.end():]
            with open(llms_path, "w", encoding="utf-8") as f:
                f.write(content)
            print("  [OK] llms.txt patched (regex)")
        else:
            print("  [WARN] llms.txt: Could not find Developer APIs section")


def patch_openapi():
    """Patch openapi.json to add China Data API paths."""
    openapi_path = os.path.join(BASE_DIR, "openapi.json")
    if not os.path.exists(openapi_path):
        print("  [SKIP] openapi.json not found")
        return
    with open(openapi_path, "r", encoding="utf-8") as f:
        spec = json.load(f)
    paths = spec.get("paths", {})
    if "/v1/api/industry" in paths:
        print("  [OK] openapi.json already has China Data APIs")
        return
    paths["/.well-known/mcp/server-card.json"] = {
        "get": {
            "summary": "MCP Server Identity Card",
            "description": "Returns MCP server identity card. Free.",
            "operationId": "mcp_server_card",
            "tags": ["raw-content"],
            "security": [],
            "responses": {"200": {"description": "MCP server card JSON"}}
        }
    }
    paths["/v1/api/industry"] = {
        "get": {
            "summary": "x402 payment discovery - China Industry Statistics",
            "description": "Returns x402 payment requirements for NBS data query.",
            "operationId": "api_industry_discovery",
            "tags": ["raw-content"], "security": [],
            "responses": {"402": {"description": "Payment Required"}}
        },
        "post": {
            "summary": "Query China industry statistics (GDP, CPI, PPI, etc.)",
            "description": "Search NBS data by keyword. Price: $0.005 USDC.",
            "operationId": "api_industry_query",
            "tags": ["raw-content"], "security": [{"x402": []}],
            "requestBody": {
                "required": True,
                "content": {"application/json": {"schema": {
                    "type": "object", "required": ["keyword"],
                    "properties": {
                        "keyword": {"type": "string", "description": "e.g. GDP, CPI, PPI"},
                        "period": {"type": "string", "default": "latest"},
                        "limit": {"type": "integer", "default": 12}
                    }
                }}}
            },
            "responses": {"200": {"description": "Statistical data"}, "402": {"description": "Payment required"}}
        }
    }
    paths["/v1/api/policy"] = {
        "get": {
            "summary": "x402 payment discovery - China Policy Search",
            "description": "Returns x402 payment requirements for policy search.",
            "operationId": "api_policy_discovery",
            "tags": ["raw-content"], "security": [],
            "responses": {"402": {"description": "Payment Required"}}
        },
        "post": {
            "summary": "Search Chinese government policy documents",
            "description": "Search policies by keyword. Price: $0.005 USDC.",
            "operationId": "api_policy_query",
            "tags": ["raw-content"], "security": [{"x402": []}],
            "requestBody": {
                "required": True,
                "content": {"application/json": {"schema": {
                    "type": "object", "required": ["keyword"],
                    "properties": {
                        "keyword": {"type": "string"},
                        "date_from": {"type": "string", "description": "YYYY-MM-DD"},
                        "limit": {"type": "integer", "default": 10}
                    }
                }}}
            },
            "responses": {"200": {"description": "Policy results"}, "402": {"description": "Payment required"}}
        }
    }
    paths["/v1/api/company"] = {
        "get": {
            "summary": "x402 payment discovery - China Enterprise Credit",
            "description": "Returns x402 payment requirements for company query.",
            "operationId": "api_company_discovery",
            "tags": ["raw-content"], "security": [],
            "responses": {"402": {"description": "Payment Required"}}
        },
        "post": {
            "summary": "Query Chinese enterprise credit information",
            "description": "Query company registration info. Price: $0.003 USDC.",
            "operationId": "api_company_query",
            "tags": ["raw-content"], "security": [{"x402": []}],
            "requestBody": {
                "required": True,
                "content": {"application/json": {"schema": {
                    "type": "object", "required": ["name"],
                    "properties": {
                        "name": {"type": "string", "description": "Company name"},
                        "credit_code": {"type": "string", "description": "18-digit code"}
                    }
                }}}
            },
            "responses": {"200": {"description": "Company info"}, "402": {"description": "Payment required"}}
        }
    }
    spec["paths"] = paths
    with open(openapi_path, "w", encoding="utf-8") as f:
        json.dump(spec, f, ensure_ascii=False, indent=2)
    print("  [OK] openapi.json patched (" + str(len(paths)) + " paths)")


def patch_catalog():
    """Patch catalog.json to replace old api-policy with 3 new APIs."""
    catalog_path = os.path.join(BASE_DIR, "catalog.json")
    if not os.path.exists(catalog_path):
        print("  [SKIP] catalog.json not found")
        return
    with open(catalog_path, "r", encoding="utf-8") as f:
        catalog = json.load(f)
    assets = catalog.get("assets", [])
    if any(a.get("id") == "api-industry" for a in assets):
        print("  [OK] catalog.json already has China Data APIs")
        return
    # Remove old api-policy (price=90)
    assets = [a for a in assets if not (a.get("id") == "api-policy" and a.get("price") == 90)]
    # Add 3 new APIs
    new_apis = [
        {
            "id": "api-industry",
            "name": "China Industry Statistics API",
            "name_en": "China Industry Statistics API",
            "kind": "api", "type": "api",
            "type_label_en": "\U0001f6e0\ufe0f API",
            "domain": ["industry", "china-data"],
            "description": "\u67e5\u8be2\u56fd\u5bb6\u7edf\u8ba1\u5c40\u7ecf\u6d4e\u6570\u636e\uff0c\u5982GDP\u3001CPI\u3001PPI\u7b49\u3002\u6309\u5173\u952e\u8bcd\u641c\u7d22\uff0c\u8fd4\u56de\u7ed3\u6784\u5316\u65f6\u95f4\u5e8f\u5217\u6570\u636e\u3002",
            "description_en": "Query China NBS economic data (GDP, CPI, PPI, etc.) by keyword.",
            "tags": ["\u7edf\u8ba1", "\u7ecf\u6d4e\u6570\u636e"],
            "tags_en": ["statistics", "economic data"],
            "price": 0.005, "currency": "USDC", "payment": "x402",
            "payment_method": ["x402"], "format": ["API"],
            "endpoint": "/v1/api/industry",
            "status": "available", "published": "2026-08-16", "listed_at": "2026-08-16",
            "shelf": "developer", "sample": "none",
            "files": [], "source_file": None, "version": 1,
            "preview_files": [], "delivery": "auto"
        },
        {
            "id": "api-policy",
            "name": "China Policy Search API",
            "name_en": "China Policy Search API",
            "kind": "api", "type": "api",
            "type_label_en": "\U0001f6e0\ufe0f API",
            "domain": ["policy", "china-data"],
            "description": "\u641c\u7d22\u4e2d\u56fd\u653f\u5e9c\u653f\u7b56\u6587\u4ef6\uff0c\u8fd4\u56de\u6807\u9898\u3001\u53d1\u6587\u5355\u4f4d\u3001\u6587\u53f7\u3001\u65e5\u671f\u3001\u6458\u8981\u548c\u539f\u6587\u94fe\u63a5\u3002",
            "description_en": "Search Chinese government policy documents by keyword.",
            "tags": ["\u653f\u7b56", "\u653f\u5e9c\u6587\u4ef6"],
            "tags_en": ["policy", "government documents"],
            "price": 0.005, "currency": "USDC", "payment": "x402",
            "payment_method": ["x402"], "format": ["API"],
            "endpoint": "/v1/api/policy",
            "status": "available", "published": "2026-08-16", "listed_at": "2026-08-16",
            "shelf": "developer", "sample": "none",
            "files": [], "source_file": None, "version": 1,
            "preview_files": [], "delivery": "auto"
        },
        {
            "id": "api-company",
            "name": "China Enterprise Credit API",
            "name_en": "China Enterprise Credit API",
            "kind": "api", "type": "api",
            "type_label_en": "\U0001f6e0\ufe0f API",
            "domain": ["business", "china-data"],
            "description": "\u67e5\u8be2\u4e2d\u56fd\u4f01\u4e1a\u5de5\u5546\u4fe1\u606f\uff0c\u8fd4\u56de\u4f01\u4e1a\u540d\u79f0\u3001\u7edf\u4e00\u793e\u4f1a\u4fe1\u7528\u4ee3\u7801\u3001\u6cd5\u5b9a\u4ee3\u8868\u4eba\u3001\u6ce8\u518c\u8d44\u672c\u7b49\u3002",
            "description_en": "Query Chinese enterprise credit information.",
            "tags": ["\u4f01\u4e1a", "\u5de5\u5546\u4fe1\u606f"],
            "tags_en": ["enterprise", "business registration"],
            "price": 0.003, "currency": "USDC", "payment": "x402",
            "payment_method": ["x402"], "format": ["API"],
            "endpoint": "/v1/api/company",
            "status": "available", "published": "2026-08-16", "listed_at": "2026-08-16",
            "shelf": "developer", "sample": "none",
            "files": [], "source_file": None, "version": 1,
            "preview_files": [], "delivery": "auto"
        }
    ]
    assets.extend(new_apis)
    catalog["assets"] = assets
    with open(catalog_path, "w", encoding="utf-8") as f:
        json.dump(catalog, f, ensure_ascii=False, indent=2)
    print("  [OK] catalog.json patched (" + str(len(assets)) + " assets)")


# ============================================================
# Main Deployment
# ============================================================


def main():
    overall_ok = True

    # ---- Step 1: Stop the AgentBridge service ----
    print_step("Step 1: Stop AgentBridge service")
    rc, out, err = run_cmd("nssm stop " + SERVICE_NAME)
    if rc == 0:
        print("  [OK] Service stopped.")
    else:
        print("  [WARN] nssm stop returned code " + str(rc) + " (service may already be stopped)")
        if out:
            print("  stdout: " + out.strip())
    # Give it a moment to release file locks
    time.sleep(2)

    # ---- Step 2: Create needed directories ----
    print_step("Step 2: Create directories")
    dirs_to_create = [
        BASE_DIR,
        os.path.join(BASE_DIR, "mcp"),
        os.path.join(BASE_DIR, ".well-known"),
        os.path.join(BASE_DIR, ".well-known", "mcp"),
    ]
    for d in dirs_to_create:
        os.makedirs(d, exist_ok=True)
        print("  [OK] Directory ready: " + d)

    # ---- Step 3: Write each file from embedded base64 ----
    print_step("Step 3: Write files from embedded content")
    written_files = []
    for b64_var, rel_path, desc, is_json in FILES:
        dest = os.path.join(BASE_DIR, rel_path)
        print("  Writing: " + desc + " -> " + dest)
        write_file_from_b64(b64_var, dest)
        written_files.append((dest, is_json, desc))

    # ---- Step 4: Run patch_servercard.py ----
    print_step("Step 4: Run patch_servercard.py to patch main.py")
    patch_script = os.path.join(BASE_DIR, "patch_servercard.py")
    if os.path.exists(patch_script):
        rc, out, err = run_cmd(
            sys.executable + " " + chr(34) + patch_script + chr(34),
            check=False,
        )
        if out:
            for line in out.strip().splitlines():
                print("  " + line)
        if rc == 0:
            print("  [OK] patch_servercard.py completed.")
        else:
            print("  [WARN] patch_servercard.py returned code " + str(rc))
            if err:
                print("  stderr: " + err.strip())
    else:
        print("  [SKIP] patch_servercard.py not found at " + patch_script)

    # ---- Step 4b: Patch documentation files (llms.txt, openapi.json, catalog.json) ----
    print_step("Step 4b: Patch documentation files")
    try:
        patch_llms()
    except Exception as e:
        print("  [ERROR] llms.txt: " + str(e))
    try:
        patch_openapi()
    except Exception as e:
        print("  [ERROR] openapi.json: " + str(e))
    try:
        patch_catalog()
    except Exception as e:
        print("  [ERROR] catalog.json: " + str(e))

    # ---- Step 5: Verify Python syntax ----
    print_step("Step 5: Verify Python syntax")
    py_files = [
        os.path.join(BASE_DIR, "china_data_api.py"),
        os.path.join(BASE_DIR, "mcp", "server.py"),
        os.path.join(BASE_DIR, "patch_servercard.py"),
        os.path.join(BASE_DIR, "main.py"),
    ]
    for pf in py_files:
        if os.path.exists(pf):
            if not verify_python_syntax(pf):
                overall_ok = False
        else:
            print("  [SKIP] File not found: " + pf)

    # ---- Step 6: Validate JSON files ----
    print_step("Step 6: Validate JSON files")
    json_files = [
        os.path.join(BASE_DIR, ".well-known", "mcp", "server-card.json"),
    ]
    for jf in json_files:
        if os.path.exists(jf):
            if not validate_json_file(jf):
                overall_ok = False
        else:
            print("  [SKIP] File not found: " + jf)

    # ---- Step 7: Restart the AgentBridge service ----
    print_step("Step 7: Restart AgentBridge service")
    rc, out, err = run_cmd("nssm start " + SERVICE_NAME)
    if rc == 0:
        print("  [OK] Service started.")
    else:
        print("  [FAIL] nssm start returned code " + str(rc))
        if err:
            print("  stderr: " + err.strip())
        overall_ok = False

    # ---- Step 8: Wait 15 seconds for service to be ready ----
    print_step("Step 8: Wait 15 seconds for service to initialize")
    for i in range(15, 0, -1):
        print("  Waiting... " + str(i) + "s remaining")
        time.sleep(1)
    print("  [OK] Wait complete.")

    # ---- Step 9 & 10: Test endpoints and print PASS/FAIL ----
    print_step("Step 9 & 10: Test endpoints")
    tests = [
        (BASE_URL + "/health",          200),
        (BASE_URL + "/v1/api/industry", 402),
        (BASE_URL + "/v1/api/policy",   402),
        (BASE_URL + "/v1/api/company",  402),
    ]
    test_results = []
    for url, expected in tests:
        result = test_endpoint(url, expected)
        test_results.append(result)
        if not result:
            overall_ok = False

    # ---- Summary ----
    print_step("Deployment Summary")
    passed = sum(1 for r in test_results if r)
    total = len(test_results)
    print("  Endpoint tests: " + str(passed) + "/" + str(total) + " passed")
    if overall_ok and passed == total:
        print("  [SUCCESS] All checks passed! Deployment complete.")
        return 0
    else:
        print("  [WARNING] Some checks failed. Please review the output above.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
